// src/pages/permission/OpsGroupManagement.tsx
import { useEffect, useMemo, useState, Fragment, type ReactNode } from 'react';
import {
  INITIAL_MEMBERS,
  avaColor,
  type Member,
} from './data';
import {
  INITIAL_OPS_GROUPS,
  INITIAL_OPS_MEMBERS,
  OPS_CHANNELS,
  OPS_ROLE_COLOR,
  OPS_ROLE_LABEL,
  nowStamp,
  newGroupId,
  opsMemberSource,
  type OpsChannel,
  type OpsChannelGroups,
  type OpsChannelMembers,
  type OpsGroup,
  type OpsMember,
  type OpsRole,
} from './opsGroupData';
import {
  Modal, ToastWrap, useToasts,
  IconArrow, IconMore, IconSearch, IconWarn, IconXsm,
  MemberPickPanel,
} from './shared';
import MoreActions, { type MoreActionItem } from '../../components/MoreActions';
import BubbleSelect from '../../components/BubbleSelect';
import './style.css';

type ModalState =
  | { kind: 'createGroup'; step: 1; name?: string }
  | { kind: 'createGroup'; step: 2; name: string }
  | { kind: 'editGroup'; group: OpsGroup }
  | { kind: 'addSub'; role: OpsRole; parentId: string; group: OpsGroup }
  | { kind: 'transfer'; entry: OpsMember; group: OpsGroup }
  | { kind: 'confirm'; title: string; msg: ReactNode; okText: string; onOk: () => void };

function RoleTag({ role }: { role: OpsRole }) {
  const c = OPS_ROLE_COLOR[role];
  return <span className="og-role-tag" style={{ color: c, background: `${c}14` }}>{OPS_ROLE_LABEL[role]}</span>;
}

/* 操作列规范：竖排直出最多两个，超出收进「更多」气泡 */
function ActionStack({ items }: { items: MoreActionItem[] }) {
  return (
    <div className="og-act-stack">
      {items.slice(0, 2).map((it) => (
        <button key={it.label} type="button" className={`text-link${it.danger ? ' danger' : ''}`} onClick={it.onClick}>{it.label}</button>
      ))}
      {items.length > 2 && <MoreActions items={items.slice(2)} />}
    </div>
  );
}

export default function OpsGroupManagement() {
  const [groups, setGroups] = useState<OpsChannelGroups>(INITIAL_OPS_GROUPS);
  const [members, setMembers] = useState<OpsChannelMembers>(INITIAL_OPS_MEMBERS);
  const [channel, setChannel] = useState<OpsChannel>('taobao');
  const [gq, setGq] = useState('');
  const [selGroup, setSelGroup] = useState('');
  const [expSpecs, setExpSpecs] = useState<Set<string>>(new Set());
  const [modal, setModal] = useState<ModalState | null>(null);
  const { toasts, pushToast } = useToasts();

  const channelGroups = groups[channel];
  const channelMembers = members[channel];
  const channelLabel = OPS_CHANNELS.find((c) => c.key === channel)?.label ?? '';

  const mutateGroups = (fn: (list: OpsGroup[]) => OpsGroup[]) => {
    setGroups((prev) => ({ ...prev, [channel]: fn(prev[channel]) }));
  };
  const mutateMembers = (fn: (list: OpsMember[]) => OpsMember[]) => {
    setMembers((prev) => ({ ...prev, [channel]: fn(prev[channel]) }));
  };

  const groupViews = useMemo(() => {
    return channelGroups.map((g) => {
      const leader = channelMembers.find((m) => m.groupId === g.id && m.role === 'leader');
      const specs = channelMembers.filter((m) => m.groupId === g.id && m.role === 'specialist');
      const size = channelMembers.filter((m) => m.groupId === g.id).length;
      return { group: g, leader, specs, size };
    });
  }, [channelGroups, channelMembers]);

  const visibleGroups = useMemo(() => {
    const q = gq.trim().toLowerCase();
    if (!q) return groupViews;
    return groupViews.filter(({ group, leader, specs }) => {
      if (group.name.toLowerCase().includes(q)) return true;
      if (leader?.name.toLowerCase().includes(q)) return true;
      return specs.some((s) => s.name.toLowerCase().includes(q));
    });
  }, [groupViews, gq]);

  const activeView = visibleGroups.find((v) => v.group.id === selGroup) ?? visibleGroups[0];
  const activeGroup = activeView?.group;
  const activeLeader = activeView?.leader;
  const activeSpecs = activeView?.specs ?? [];

  useEffect(() => {
    setSelGroup('');
  }, [channel]);

  useEffect(() => {
    setExpSpecs(new Set());
  }, [activeGroup?.id]);

  const toggleSpec = (id: string) => {
    setExpSpecs((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  const isMemberTaken = (memberId: string) => channelMembers.some((m) => m.memberId === memberId);

  const createGroup = (name: string, leaderId: string) => {
    if (isMemberTaken(leaderId)) {
      pushToast('该成员在当前平台已有运营归属', 'error');
      return;
    }
    const src = opsMemberSource(leaderId);
    if (!src) return;
    const gid = newGroupId();
    mutateGroups((list) => [...list, { id: gid, channel, name, leaderId, createdAt: nowStamp() }]);
    mutateMembers((list) => [
      ...list,
      { memberId: leaderId, name: src.name, role: 'leader', groupId: gid, parentId: null, addedBy: '管理员', addedAt: nowStamp() },
    ]);
    setSelGroup(gid);
    pushToast(`已创建运营组「${name}」`);
    setModal(null);
  };

  const renameGroup = (groupId: string, name: string) => {
    mutateGroups((list) => list.map((g) => (g.id === groupId ? { ...g, name } : g)));
    pushToast('已更新组名');
    setModal(null);
  };

  const deleteGroup = (group: OpsGroup) => {
    const size = channelMembers.filter((m) => m.groupId === group.id).length;
    if (size > 0) {
      pushToast('组内仍有成员，无法删除', 'error');
      return;
    }
    mutateGroups((list) => list.filter((g) => g.id !== group.id));
    pushToast('已删除运营组');
  };

  const addSubordinates = (groupId: string, role: OpsRole, parentId: string, ids: string[]) => {
    if (ids.some((id) => isMemberTaken(id))) {
      pushToast('部分成员在当前平台已有运营归属', 'error');
      return;
    }
    const srcs = ids.map((id) => opsMemberSource(id)).filter((s): s is Member => !!s);
    if (!srcs.length) return;
    mutateMembers((list) => [
      ...list,
      ...srcs.map((s) => ({ memberId: s.id, name: s.name, role, groupId, parentId, addedBy: '管理员', addedAt: nowStamp() })),
    ]);
    pushToast(`已添加 ${srcs.length} 名${OPS_ROLE_LABEL[role]}`);
    setModal(null);
  };

  const transferRole = (entry: OpsMember, fromGroup: OpsGroup, targetGroupId: string, targetParentId: string) => {
    const targetGroup = channelGroups.find((g) => g.id === targetGroupId);
    if (!targetGroup) return;

    if (entry.role === 'leader') {
      const oldLeaderId = targetGroup.leaderId;
      mutateGroups((list) => list.map((g) => {
        if (g.id === fromGroup.id) return { ...g, leaderId: '' };
        if (g.id === targetGroupId) return { ...g, leaderId: entry.memberId };
        return g;
      }));
      mutateMembers((list) => list.map((m) => {
        if (m.memberId === entry.memberId) {
          return { ...m, groupId: targetGroupId, parentId: null };
        }
        if (oldLeaderId && m.memberId === oldLeaderId && m.groupId === targetGroupId) {
          return { ...m, role: 'specialist', parentId: entry.memberId };
        }
        if (m.parentId === entry.memberId && m.groupId === fromGroup.id) {
          return { ...m, groupId: targetGroupId };
        }
        return m;
      }));
      pushToast('已转交组长');
    } else if (entry.role === 'specialist') {
      mutateMembers((list) => list.map((m) => {
        if (m.memberId === entry.memberId) {
          return { ...m, groupId: targetGroupId, parentId: targetParentId };
        }
        if (m.parentId === entry.memberId && m.groupId === fromGroup.id) {
          return { ...m, groupId: targetGroupId, parentId: targetParentId };
        }
        return m;
      }));
      pushToast('已转交专员');
    } else {
      mutateMembers((list) => list.map((m) =>
        m.memberId === entry.memberId ? { ...m, groupId: targetGroupId, parentId: targetParentId } : m
      ));
      pushToast('已转交助理');
    }
    setModal(null);
  };

  const transferLeader = (group: OpsGroup, oldLeader: OpsMember, newLeaderId: string) => {
    if (isMemberTaken(newLeaderId)) {
      pushToast('该成员在当前平台已有运营归属', 'error');
      return;
    }
    const src = opsMemberSource(newLeaderId);
    if (!src) return;
    mutateGroups((list) => list.map((g) => (g.id === group.id ? { ...g, leaderId: newLeaderId } : g)));
    mutateMembers((list) => [
      ...list.map((m) => (m.memberId === oldLeader.memberId ? { ...m, role: 'specialist' as OpsRole, parentId: newLeaderId } : m)),
      { memberId: newLeaderId, name: src.name, role: 'leader' as OpsRole, groupId: group.id, parentId: null, addedBy: oldLeader.name, addedAt: nowStamp() },
    ]);
    pushToast(`已将组长转交给「${src.name}」`);
    setModal(null);
  };

  const transferSpecialist = (group: OpsGroup, oldSpec: OpsMember, newSpecId: string) => {
    if (isMemberTaken(newSpecId)) {
      pushToast('该成员在当前平台已有运营归属', 'error');
      return;
    }
    const src = opsMemberSource(newSpecId);
    if (!src) return;
    mutateMembers((list) => [
      ...list.map((m) => {
        if (m.memberId === oldSpec.memberId) return { ...m, role: 'assistant' as OpsRole, parentId: newSpecId };
        if (m.role === 'assistant' && m.parentId === oldSpec.memberId) return { ...m, parentId: newSpecId };
        return m;
      }),
      { memberId: newSpecId, name: src.name, role: 'specialist' as OpsRole, groupId: group.id, parentId: oldSpec.parentId, addedBy: oldSpec.name, addedAt: nowStamp() },
    ]);
    pushToast(`已将专员转交给「${src.name}」`);
    setModal(null);
  };

  const closeModal = () => setModal(null);

  return (
    <>
      <div className="og-wrap">
      <div className="og-toolbar">
        <div className="og-tabs">
          {OPS_CHANNELS.map((c) => (
            <button key={c.key} className={`og-tab ${channel === c.key ? 'active' : ''}`} onClick={() => setChannel(c.key)}>
              {c.label}
            </button>
          ))}
        </div>
        <div className="og-tools">
          <div className="input-icon og-search">
            <span className="ic"><IconSearch /></span>
            <input className="input" placeholder="搜索组名 / 组长 / 成员" value={gq} onChange={(e) => setGq(e.target.value)} />
          </div>
          <button className="btn primary" onClick={() => setModal({ kind: 'createGroup', step: 1 })}>+ 新建运营组</button>
        </div>
      </div>
      
      <div className="og-md">
        <div className="og-md-left">
          {visibleGroups.length ? visibleGroups.map(({ group, leader, size }) => (
            <div
              key={group.id}
              className={`og-md-item ${activeGroup?.id === group.id ? 'active' : ''}`}
              onClick={() => setSelGroup(group.id)}
            >
              <div className="og-md-item-hd">
                <span className="og-md-name">{group.name}</span>
                <span className="og-g-count">{size}人</span>
                <span className="og-md-more" onClick={(e) => e.stopPropagation()}>
                  <MoreActions
                    trigger={<IconMore />}
                    items={[
                      { label: '重命名', onClick: () => setModal({ kind: 'editGroup', group }) },
                      { label: '删除组织', danger: true, onClick: () => deleteGroup(group) },
                    ]}
                  />
                </span>
              </div>
              <div className="og-md-item-sub">
                {leader && <span className="og-lead-ava" style={{ background: avaColor(leader.name) }}>{leader.name.slice(0, 1)}</span>}
                组长：{leader?.name ?? '未指定'}
              </div>
            </div>
          )) : (
            <div className="empty" style={{ padding: '20px 0' }}>无匹配运营组</div>
          )}
        </div>

        <div className="og-md-right">
          {activeView && activeGroup ? (
            <div className="og-detail">
              <div className="og-detail-hd">
                <span className="og-g-name">{activeGroup.name}</span>
              </div>
              <div className="og-detail-body">
                <div className="og-table">
                  <div className="og-tr head">
                    <div className="og-cell">成员名称</div>
                    <div className="og-cell">职位</div>
                    <div className="og-cell">添加时间</div>
                    <div className="og-cell">添加人</div>
                    <div className="og-cell">操作</div>
                  </div>
                  {activeLeader ? (
                    <div className="og-tr">
                      <div className="og-cell og-td-name">
                        <span className="og-ava" style={{ background: avaColor(activeLeader.name) }}>{activeLeader.name.slice(0, 1)}</span>
                        <span className="og-cell-nm">{activeLeader.name}</span>
                      </div>
                      <div className="og-cell"><RoleTag role="leader" /></div>
                      <div className="og-cell og-td-dim">{activeLeader.addedAt}</div>
                      <div className="og-cell og-td-dim">{activeLeader.addedBy}</div>
                      <div className="og-cell">
                        <ActionStack items={[
                          { label: '转交组长', onClick: () => setModal({ kind: 'transfer', entry: activeLeader, group: activeGroup }) },
                          { label: '添加专员', onClick: () => setModal({ kind: 'addSub', role: 'specialist', parentId: activeLeader.memberId, group: activeGroup }) },
                        ]} />
                      </div>
                    </div>
                  ) : (
                    <div className="og-tr-empty">该组暂无组长</div>
                  )}
                  {activeSpecs.map((sp) => {
                    const assis = channelMembers.filter((m) => m.parentId === sp.memberId && m.role === 'assistant');
                    const open = expSpecs.has(sp.memberId);
                    return (
                      <Fragment key={sp.memberId}>
                        <div className="og-tr spec" onClick={() => toggleSpec(sp.memberId)}>
                          <div className="og-cell og-td-name d1">
                            <span className={`arrow ${open ? 'open' : ''} ${assis.length ? '' : 'leaf'}`}><IconArrow /></span>
                            <span className="og-ava" style={{ background: avaColor(sp.name) }}>{sp.name.slice(0, 1)}</span>
                            <span className="og-cell-nm">{sp.name}</span>
                            {assis.length > 0 && <span className="og-g-count">{assis.length}助理</span>}
                          </div>
                          <div className="og-cell"><RoleTag role="specialist" /></div>
                          <div className="og-cell og-td-dim">{sp.addedAt}</div>
                          <div className="og-cell og-td-dim">{sp.addedBy}</div>
                          <div className="og-cell" onClick={(e) => e.stopPropagation()}>
                            <ActionStack items={[
                              { label: '转交专员', onClick: () => setModal({ kind: 'transfer', entry: sp, group: activeGroup }) },
                              { label: '添加助理', onClick: () => setModal({ kind: 'addSub', role: 'assistant', parentId: sp.memberId, group: activeGroup }) },
                            ]} />
                          </div>
                        </div>
                        {open && (
                          assis.length ? assis.map((a) => (
                            <div key={a.memberId} className="og-tr sub">
                              <div className="og-cell og-td-name d2">
                                <span className="arrow leaf"><IconArrow /></span>
                                <span className="og-ava sm" style={{ background: avaColor(a.name) }}>{a.name.slice(0, 1)}</span>
                                <span className="og-cell-nm">{a.name}</span>
                              </div>
                              <div className="og-cell"><RoleTag role="assistant" /></div>
                              <div className="og-cell og-td-dim">{a.addedAt}</div>
                              <div className="og-cell og-td-dim">{a.addedBy}</div>
                              <div className="og-cell og-td-dim">-</div>
                            </div>
                          )) : (
                            <div className="og-tr sub">
                              <div className="og-cell og-td-name d2">
                                <span className="arrow leaf"><IconArrow /></span>
                                <span className="og-td-dim">暂无助理</span>
                              </div>
                              <div className="og-cell" />
                              <div className="og-cell" />
                              <div className="og-cell" />
                              <div className="og-cell" />
                            </div>
                          )
                        )}
                      </Fragment>
                    );
                  })}
                  {activeLeader && activeSpecs.length === 0 && (
                    <div className="og-tr-empty">暂无专员，可在组长行「添加专员」</div>
                  )}
                </div>
              </div>
            </div>
          ) : (
            <div className="empty" style={{ padding: '60px 0' }}>请选择左侧运营组</div>
          )}
        </div>
      </div>
      </div>

      {modal?.kind === 'createGroup' && modal.step === 1 && (
        <CreateGroupStep1Modal
          channelLabel={channelLabel}
          onNext={(name) => setModal({ kind: 'createGroup', step: 2, name })}
          onClose={closeModal}
        />
      )}
      {modal?.kind === 'createGroup' && modal.step === 2 && (
        <CreateGroupStep2Modal
          name={modal.name}
          channelLabel={channelLabel}
          taken={new Set(channelMembers.map((m) => m.memberId))}
          onConfirm={(leaderId) => createGroup(modal.name, leaderId)}
          onBack={() => setModal({ kind: 'createGroup', step: 1, name: modal.name })}
          onClose={closeModal}
        />
      )}
      {modal?.kind === 'editGroup' && (
        <EditGroupModal
          group={modal.group}
          onConfirm={(name) => renameGroup(modal.group.id, name)}
          onClose={closeModal}
        />
      )}
      {modal?.kind === 'addSub' && (
        <AddSubModal
          role={modal.role}
          group={modal.group}
          parentId={modal.parentId}
          channelMembers={channelMembers}
          taken={new Set(channelMembers.map((m) => m.memberId))}
          onConfirm={(ids) => addSubordinates(modal.group.id, modal.role, modal.parentId, ids)}
          onClose={closeModal}
        />
      )}
      {modal?.kind === 'transfer' && (modal.entry.role === 'assistant' ? (
        <TransferModal
          entry={modal.entry}
          group={modal.group}
          channelGroups={channelGroups}
          channelMembers={channelMembers}
          onConfirm={(targetGroupId, targetParentId) => transferRole(modal.entry, modal.group, targetGroupId, targetParentId)}
          onClose={closeModal}
        />
      ) : (
        <TransferPersonModal
          entry={modal.entry}
          group={modal.group}
          role={modal.entry.role === 'leader' ? 'leader' : 'specialist'}
          taken={new Set(channelMembers.map((m) => m.memberId))}
          onConfirm={(memberId) => (modal.entry.role === 'leader'
            ? transferLeader(modal.group, modal.entry, memberId)
            : transferSpecialist(modal.group, modal.entry, memberId))}
          onClose={closeModal}
        />
      ))}
      {modal?.kind === 'confirm' && (
        <Modal title={modal.title} onClose={closeModal} foot={
          <>
            <button className="btn" onClick={closeModal}>取消</button>
            <button className="btn danger" onClick={() => { modal.onOk(); closeModal(); }}>{modal.okText}</button>
          </>
        }>
          <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
            <span style={{ color: 'var(--danger)', flexShrink: 0 }}><IconWarn /></span>
            <div style={{ color: 'var(--text-2)', lineHeight: 1.6, paddingTop: 1 }}>{modal.msg}</div>
          </div>
        </Modal>
      )}

      <ToastWrap toasts={toasts} />
    </>
  );
}

function CreateGroupStep1Modal({ channelLabel, onNext, onClose }: {
  channelLabel: string;
  onNext: (name: string) => void;
  onClose: () => void;
}) {
  const [name, setName] = useState('');
  return (
    <Modal title="新建运营组" sub={`步骤 1/2 · 渠道：${channelLabel}`} size="md" onClose={onClose} foot={
      <>
        <button className="btn" onClick={onClose}>取消</button>
        <button className="btn primary" onClick={() => { if (!name.trim()) return; onNext(name.trim()); }}>下一步：选择组长</button>
      </>
    }>
      <div className="form-item">
        <label>运营组名称</label>
        <input className="input" value={name} placeholder="请输入组名" maxLength={20} onChange={(e) => setName(e.target.value)} />
      </div>
    </Modal>
  );
}

function CreateGroupStep2Modal({ name, channelLabel, taken, onConfirm, onBack, onClose }: {
  name: string;
  channelLabel: string;
  taken: Set<string>;
  onConfirm: (leaderId: string) => void;
  onBack: () => void;
  onClose: () => void;
}) {
  const [picked, setPicked] = useState<Set<string>>(new Set());

  const pool = useMemo(() => INITIAL_MEMBERS.filter((m) => m.status !== 'pending'), []);
  const pickedMembers = pool.filter((m) => picked.has(m.id));
  const pickedSrc = pickedMembers[0];

  return (
    <Modal title="选择组长" sub={`步骤 2/2 · 组名：${name} · 渠道：${channelLabel}`} size="xl" onClose={onClose} foot={
      <>
        <button className="btn" onClick={onBack}>上一步</button>
        <button className="btn" onClick={onClose}>取消</button>
        <button className="btn primary" onClick={() => { if (!pickedSrc) return; onConfirm(pickedSrc.id); }}>创建</button>
      </>
    }>
      <div className="member-transfer">
        <MemberPickPanel
          members={pool}
          selectedIds={picked}
          disabledIds={taken}
          noDeptPick
          onToggle={(id) => setPicked((prev) => (prev.has(id) ? new Set() : new Set([id])))}
          onBulk={() => {}}
        />
        <PickedSide picked={pickedMembers} max={1} onRemove={() => setPicked(new Set())} />
      </div>
    </Modal>
  );
}

function EditGroupModal({ group, onConfirm, onClose }: {
  group: OpsGroup;
  onConfirm: (name: string) => void;
  onClose: () => void;
}) {
  const [name, setName] = useState(group.name);
  return (
    <Modal title="编辑运营组" size="md" onClose={onClose} foot={
      <>
        <button className="btn" onClick={onClose}>取消</button>
        <button className="btn primary" onClick={() => { if (!name.trim()) return; onConfirm(name.trim()); }}>保存</button>
      </>
    }>
      <div className="form-item">
        <label>运营组名称</label>
        <input className="input" value={name} placeholder="请输入组名" maxLength={20} onChange={(e) => setName(e.target.value)} />
      </div>
    </Modal>
  );
}

function AddSubModal({ role, group, parentId, channelMembers, taken, onConfirm, onClose }: {
  role: OpsRole;
  group: OpsGroup;
  parentId: string;
  channelMembers: OpsMember[];
  taken: Set<string>;
  onConfirm: (ids: string[]) => void;
  onClose: () => void;
}) {
  const [picked, setPicked] = useState<Set<string>>(new Set());

  const parent = channelMembers.find((m) => m.memberId === parentId);
  const pool = useMemo(() => INITIAL_MEMBERS.filter((m) => m.status !== 'pending'), []);
  const pickedMembers = pool.filter((m) => picked.has(m.id));

  return (
    <Modal title={`添加${OPS_ROLE_LABEL[role]}`} sub={`组：${group.name} · 上级：${parent?.name ?? ''}`} size="xl" onClose={onClose} foot={
      <>
        <button className="btn" onClick={onClose}>取消</button>
        <button className="btn primary" onClick={() => { if (!picked.size) return; onConfirm([...picked]); }}>确认添加</button>
      </>
    }>
      <div className="member-transfer">
        <MemberPickPanel
          members={pool}
          selectedIds={picked}
          disabledIds={taken}
          noDeptPick
          onToggle={(id) => setPicked((prev) => {
            const next = new Set(prev);
            if (next.has(id)) next.delete(id); else next.add(id);
            return next;
          })}
          onBulk={() => {}}
        />
        <PickedSide
          picked={pickedMembers}
          max={1000}
          onRemove={(id) => setPicked((prev) => {
            const next = new Set(prev);
            next.delete(id);
            return next;
          })}
        />
      </div>
    </Modal>
  );
}

function TransferModal({ entry, group, channelGroups, channelMembers, onConfirm, onClose }: {
  entry: OpsMember;
  group: OpsGroup;
  channelGroups: OpsGroup[];
  channelMembers: OpsMember[];
  onConfirm: (targetGroupId: string, targetParentId: string) => void;
  onClose: () => void;
}) {
  const [targetGroupId, setTargetGroupId] = useState(group.id);
  const [targetParentId, setTargetParentId] = useState('');

  const parentCandidates = useMemo(() => {
    if (entry.role === 'specialist') {
      return channelMembers.filter((m) => m.groupId === targetGroupId && m.role === 'leader' && m.memberId !== entry.memberId);
    }
    if (entry.role === 'assistant') {
      return channelMembers.filter((m) => m.groupId === targetGroupId && m.role === 'specialist' && m.memberId !== entry.memberId);
    }
    return [];
  }, [entry.role, targetGroupId, channelMembers]);

  useEffect(() => {
    setTargetParentId(parentCandidates[0]?.memberId ?? '');
  }, [targetGroupId, parentCandidates]);

  return (
    <Modal title={`转交${OPS_ROLE_LABEL[entry.role]}`} sub={`当前：${entry.name} · 组：${group.name}`} size="md" onClose={onClose} foot={
      <>
        <button className="btn" onClick={onClose}>取消</button>
        <button className="btn primary" onClick={() => { if (!targetGroupId || !targetParentId) return; onConfirm(targetGroupId, targetParentId); }}>确认转交</button>
      </>
    }>
      <div className="form-item">
        <label>目标分组</label>
        <BubbleSelect
          className="input"
          value={targetGroupId}
          onChange={(v) => setTargetGroupId(v)}
          options={channelGroups.map((g) => ({ value: g.id, label: g.name }))}
        />
      </div>
      <div className="form-item">
        <label>{entry.role === 'specialist' ? '挂靠组长' : '挂靠专员'}</label>
        <BubbleSelect
          className="input"
          value={targetParentId || '请选择'}
          onChange={(v) => setTargetParentId(v)}
          options={parentCandidates.map((m) => ({ value: m.memberId, label: m.name }))}
        />
      </div>
    </Modal>
  );
}

/* 转交组长/专员：唤起成员选择组件（仅可选人、已有归属禁选），一对一交接 */
function TransferPersonModal({ entry, group, role, taken, onConfirm, onClose }: {
  entry: OpsMember;
  group: OpsGroup;
  role: 'leader' | 'specialist';
  taken: Set<string>;
  onConfirm: (memberId: string) => void;
  onClose: () => void;
}) {
  const [picked, setPicked] = useState<Set<string>>(new Set());

  const pool = useMemo(() => INITIAL_MEMBERS.filter((m) => m.status !== 'pending'), []);
  const disabled = useMemo(() => new Set([...taken, entry.memberId]), [taken, entry.memberId]);
  const pickedMembers = pool.filter((m) => picked.has(m.id));
  const pickedSrc = pickedMembers[0];
  const roleLabel = role === 'leader' ? '组长' : '专员';
  const oldLabel = role === 'leader' ? '原组长' : '原专员';
  const demoteLabel = role === 'leader' ? '专员' : '助理';

  return (
    <Modal title={`转交运营${roleLabel}`} sub={`当前：${entry.name} · 组：${group.name}`} size="xl" onClose={onClose} foot={
      <>
        <button className="btn" onClick={onClose}>取消</button>
        <button className="btn primary" onClick={() => { if (!pickedSrc) return; onConfirm(pickedSrc.id); }}>确认转交</button>
      </>
    }>
      <div className="member-transfer">
        <MemberPickPanel
          members={pool}
          selectedIds={picked}
          disabledIds={disabled}
          noDeptPick
          onToggle={(id) => setPicked((prev) => (prev.has(id) ? new Set() : new Set([id])))}
          onBulk={() => {}}
        />
        <PickedSide picked={pickedMembers} max={1} onRemove={() => setPicked(new Set())} />
      </div>
      {pickedSrc && (
        <div className="form-tip" style={{ marginTop: 10 }}>转交后：<b>{pickedSrc.name}</b> 将成为「{group.name}」{roleLabel}，{oldLabel} {entry.name} 转为{demoteLabel}。</div>
      )}
    </Modal>
  );
}

/* 已选侧栏：与「选择成员」弹窗同款 */
function PickedSide({ picked, max, onRemove }: {
  picked: Member[];
  max: number;
  onRemove: (id: string) => void;
}) {
  return (
    <div className="member-transfer-right">
      <div className="mtr-head">已选择({picked.length}/{max})</div>
      <div className="mtr-body">
        {picked.length === 0 ? (
          <div className="mtr-empty">暂未选择成员</div>
        ) : picked.map((m) => (
          <div className="mtr-selected" key={m.id}>
            <span className="og-ava" style={{ background: avaColor(m.name) }}>{m.name.slice(0, 1)}</span>
            <span className="mtr-name">{m.name}</span>
            <span className="mtr-rm" onClick={() => onRemove(m.id)}><IconXsm /></span>
          </div>
        ))}
      </div>
    </div>
  );
}

// src/pages/permission/OpsGroupManagement.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { avaColor } from './data';
import type { Member } from './data';
import ToastWrap from '../../components/ToastWrap.vue';
import Modal from '../../components/Modal.vue';
import { pushToast } from '../../components/toast';
import './style.css';
import { IconArrow, IconMore, IconSearch, IconWarn } from './permIcons';
import MoreActions from '../../components/MoreActions.vue';
import OgActionStack from './OgActionStack.vue';
import OgCreateStep1Modal from './OgCreateStep1Modal.vue';
import OgCreateStep2Modal from './OgCreateStep2Modal.vue';
import OgEditGroupModal from './OgEditGroupModal.vue';
import OgAddSubModal from './OgAddSubModal.vue';
import OgTransferModal from './OgTransferModal.vue';
import OgTransferPersonModal from './OgTransferPersonModal.vue';
import {
  INITIAL_OPS_GROUPS,
  INITIAL_OPS_MEMBERS,
  OPS_CHANNELS,
  OPS_ROLE_COLOR,
  OPS_ROLE_LABEL,
  nowStamp,
  newGroupId,
  opsMemberSource,
} from './opsGroupData';
import type { OpsChannel, OpsChannelGroups, OpsChannelMembers, OpsGroup, OpsMember, OpsRole } from './opsGroupData';

/* ---------- 弹窗状态（msg 为结构化富文本：pre + <b>bold</b> + post） ---------- */
type ConfirmMsg = { pre: string; bold?: string; post: string };
type ModalState =
  | { kind: 'createGroup'; step: 1; name?: string }
  | { kind: 'createGroup'; step: 2; name: string }
  | { kind: 'editGroup'; group: OpsGroup }
  | { kind: 'addSub'; role: OpsRole; parentId: string; group: OpsGroup }
  | { kind: 'transfer'; entry: OpsMember; group: OpsGroup }
  | { kind: 'confirm'; title: string; msg: ConfirmMsg; okText: string; onOk: () => void };

const groups = ref<OpsChannelGroups>(INITIAL_OPS_GROUPS);
const members = ref<OpsChannelMembers>(INITIAL_OPS_MEMBERS);
const channel = ref<OpsChannel>('taobao');
const gq = ref('');
const selGroup = ref('');
const expSpecs = ref<Set<string>>(new Set());
const modal = ref<ModalState | null>(null);

const channelGroups = computed(() => groups.value[channel.value]);
const channelMembers = computed(() => members.value[channel.value]);
const channelLabel = computed(() => OPS_CHANNELS.find((c) => c.key === channel.value)?.label ?? '');

const mutateGroups = (fn: (list: OpsGroup[]) => OpsGroup[]) => {
  groups.value = { ...groups.value, [channel.value]: fn(groups.value[channel.value]) };
};
const mutateMembers = (fn: (list: OpsMember[]) => OpsMember[]) => {
  members.value = { ...members.value, [channel.value]: fn(members.value[channel.value]) };
};

const groupViews = computed(() => channelGroups.value.map((g) => {
  const leader = channelMembers.value.find((m) => m.groupId === g.id && m.role === 'leader');
  const specs = channelMembers.value.filter((m) => m.groupId === g.id && m.role === 'specialist');
  const size = channelMembers.value.filter((m) => m.groupId === g.id).length;
  return { group: g, leader, specs, size };
}));

const visibleGroups = computed(() => {
  const q = gq.value.trim().toLowerCase();
  if (!q) return groupViews.value;
  return groupViews.value.filter(({ group, leader, specs }) => {
    if (group.name.toLowerCase().includes(q)) return true;
    if (leader?.name.toLowerCase().includes(q)) return true;
    return specs.some((s) => s.name.toLowerCase().includes(q));
  });
});

const activeView = computed(() => visibleGroups.value.find((v) => v.group.id === selGroup.value) ?? visibleGroups.value[0]);
const activeGroup = computed(() => activeView.value?.group);
const activeLeader = computed(() => activeView.value?.leader);
const activeSpecs = computed(() => activeView.value?.specs ?? []);

watch(channel, () => { selGroup.value = ''; });
watch(activeGroup, () => { expSpecs.value = new Set(); });

const toggleSpec = (id: string) => {
  const next = new Set(expSpecs.value);
  if (next.has(id)) next.delete(id); else next.add(id);
  expSpecs.value = next;
};

const isMemberTaken = (memberId: string) => channelMembers.value.some((m) => m.memberId === memberId);

const createGroup = (name: string, leaderId: string) => {
  if (isMemberTaken(leaderId)) {
    pushToast('该成员在当前平台已有运营归属', 'error');
    return;
  }
  const src = opsMemberSource(leaderId);
  if (!src) return;
  const gid = newGroupId();
  mutateGroups((list) => [...list, { id: gid, channel: channel.value, name, leaderId, createdAt: nowStamp() }]);
  mutateMembers((list) => [
    ...list,
    { memberId: leaderId, name: src.name, role: 'leader', groupId: gid, parentId: null, addedBy: '管理员', addedAt: nowStamp() },
  ]);
  selGroup.value = gid;
  pushToast(`已创建运营组「${name}」`);
  modal.value = null;
};

const renameGroup = (groupId: string, name: string) => {
  mutateGroups((list) => list.map((g) => (g.id === groupId ? { ...g, name } : g)));
  pushToast('已更新组名');
  modal.value = null;
};

const deleteGroup = (group: OpsGroup) => {
  const size = channelMembers.value.filter((m) => m.groupId === group.id).length;
  if (size > 0) {
    pushToast('组内仍有成员，无法删除', 'error');
    return;
  }
  mutateGroups((list) => list.filter((g) => g.id !== group.id));
  pushToast('已删除运营组');
};

const addSubordinates = (groupId: string, role: OpsRole, parentId: string, ids: string[]) => {
  if (ids.some((id) => isMemberTaken(id))) {
    pushToast('部分成员在当前平台已有运营归属', 'error');
    return;
  }
  const srcs = ids.map((id) => opsMemberSource(id)).filter((s): s is Member => !!s);
  if (!srcs.length) return;
  mutateMembers((list) => [
    ...list,
    ...srcs.map((s) => ({ memberId: s.id, name: s.name, role, groupId, parentId, addedBy: '管理员', addedAt: nowStamp() })),
  ]);
  pushToast(`已添加 ${srcs.length} 名${OPS_ROLE_LABEL[role]}`);
  modal.value = null;
};

const transferRole = (entry: OpsMember, fromGroup: OpsGroup, targetGroupId: string, targetParentId: string) => {
  const targetGroup = channelGroups.value.find((g) => g.id === targetGroupId);
  if (!targetGroup) return;

  if (entry.role === 'leader') {
    const oldLeaderId = targetGroup.leaderId;
    mutateGroups((list) => list.map((g) => {
      if (g.id === fromGroup.id) return { ...g, leaderId: '' };
      if (g.id === targetGroupId) return { ...g, leaderId: entry.memberId };
      return g;
    }));
    mutateMembers((list) => list.map((m) => {
      if (m.memberId === entry.memberId) {
        return { ...m, groupId: targetGroupId, parentId: null };
      }
      if (oldLeaderId && m.memberId === oldLeaderId && m.groupId === targetGroupId) {
        return { ...m, role: 'specialist', parentId: entry.memberId };
      }
      if (m.parentId === entry.memberId && m.groupId === fromGroup.id) {
        return { ...m, groupId: targetGroupId };
      }
      return m;
    }));
    pushToast('已转交组长');
  } else if (entry.role === 'specialist') {
    mutateMembers((list) => list.map((m) => {
      if (m.memberId === entry.memberId) {
        return { ...m, groupId: targetGroupId, parentId: targetParentId };
      }
      if (m.parentId === entry.memberId && m.groupId === fromGroup.id) {
        return { ...m, groupId: targetGroupId, parentId: targetParentId };
      }
      return m;
    }));
    pushToast('已转交专员');
  } else {
    mutateMembers((list) => list.map((m) =>
      m.memberId === entry.memberId ? { ...m, groupId: targetGroupId, parentId: targetParentId } : m
    ));
    pushToast('已转交助理');
  }
  modal.value = null;
};

const transferLeader = (group: OpsGroup, oldLeader: OpsMember, newLeaderId: string) => {
  if (isMemberTaken(newLeaderId)) {
    pushToast('该成员在当前平台已有运营归属', 'error');
    return;
  }
  const src = opsMemberSource(newLeaderId);
  if (!src) return;
  mutateGroups((list) => list.map((g) => (g.id === group.id ? { ...g, leaderId: newLeaderId } : g)));
  mutateMembers((list) => [
    ...list.map((m) => (m.memberId === oldLeader.memberId ? { ...m, role: 'specialist' as OpsRole, parentId: newLeaderId } : m)),
    { memberId: newLeaderId, name: src.name, role: 'leader' as OpsRole, groupId: group.id, parentId: null, addedBy: oldLeader.name, addedAt: nowStamp() },
  ]);
  pushToast(`已将组长转交给「${src.name}」`);
  modal.value = null;
};

const transferSpecialist = (group: OpsGroup, oldSpec: OpsMember, newSpecId: string) => {
  if (isMemberTaken(newSpecId)) {
    pushToast('该成员在当前平台已有运营归属', 'error');
    return;
  }
  const src = opsMemberSource(newSpecId);
  if (!src) return;
  mutateMembers((list) => [
    ...list.map((m) => {
      if (m.memberId === oldSpec.memberId) return { ...m, role: 'assistant' as OpsRole, parentId: newSpecId };
      if (m.role === 'assistant' && m.parentId === oldSpec.memberId) return { ...m, parentId: newSpecId };
      return m;
    }),
    { memberId: newSpecId, name: src.name, role: 'specialist' as OpsRole, groupId: group.id, parentId: oldSpec.parentId, addedBy: oldSpec.name, addedAt: nowStamp() },
  ]);
  pushToast(`已将专员转交给「${src.name}」`);
  modal.value = null;
};

const closeModal = () => { modal.value = null; };

/* RoleTag 样式 */
const roleTagStyle = (role: OpsRole) => {
  const c = OPS_ROLE_COLOR[role];
  return { color: c, background: `${c}14` };
};

const takenIds = computed(() => new Set(channelMembers.value.map((m) => m.memberId)));
const assisOf = (sp: OpsMember) => channelMembers.value.filter((m) => m.parentId === sp.memberId && m.role === 'assistant');

const openCreate = () => { modal.value = { kind: 'createGroup', step: 1 }; };
const openEditGroup = (group: OpsGroup) => { modal.value = { kind: 'editGroup', group }; };
const openTransfer = (entry: OpsMember, group: OpsGroup) => { modal.value = { kind: 'transfer', entry, group }; };
const openAddSub = (role: OpsRole, parentId: string, group: OpsGroup) => {
  modal.value = { kind: 'addSub', role, parentId, group };
};
const step2Next = (name: string) => { modal.value = { kind: 'createGroup', step: 2, name }; };
const step2Back = (name: string) => { modal.value = { kind: 'createGroup', step: 1, name }; };
const okConfirm = (m: Extract<ModalState, { kind: 'confirm' }>) => { m.onOk(); closeModal(); };

/* 组长行操作（模板回调无法收窄 activeLeader/activeGroup，统一在此守卫） */
const openLeaderTransfer = () => {
  if (activeLeader.value && activeGroup.value) openTransfer(activeLeader.value, activeGroup.value);
};
const openLeaderAddSpec = () => {
  if (activeLeader.value && activeGroup.value) openAddSub('specialist', activeLeader.value.memberId, activeGroup.value);
};

/* 弹窗确定入口（联合类型在模板回调中无法收窄，统一在此守卫） */
const step2Confirm = (leaderId: string) => {
  if (modal.value?.kind === 'createGroup' && modal.value.step === 2) createGroup(modal.value.name, leaderId);
};
const step2BackCur = () => {
  if (modal.value?.kind === 'createGroup' && modal.value.step === 2) step2Back(modal.value.name);
};
const editGroupConfirm = (name: string) => {
  if (modal.value?.kind === 'editGroup') renameGroup(modal.value.group.id, name);
};
const addSubConfirm = (ids: string[]) => {
  if (modal.value?.kind === 'addSub') addSubordinates(modal.value.group.id, modal.value.role, modal.value.parentId, ids);
};
const transferConfirm = (gid: string, pid: string) => {
  if (modal.value?.kind === 'transfer') transferRole(modal.value.entry, modal.value.group, gid, pid);
};
const transferPersonConfirm = (memberId: string) => {
  if (modal.value?.kind === 'transfer') {
    if (modal.value.entry.role === 'leader') transferLeader(modal.value.group, modal.value.entry, memberId);
    else transferSpecialist(modal.value.group, modal.value.entry, memberId);
  }
};
</script>

<template>
  <div class="og-wrap">
    <div class="og-toolbar">
      <div class="og-tabs">
        <button
          v-for="c in OPS_CHANNELS"
          :key="c.key"
          class="og-tab"
          :class="channel === c.key ? 'active' : ''"
          @click="channel = c.key"
        >{{ c.label }}</button>
      </div>
      <div class="og-tools">
        <div class="input-icon og-search">
          <span class="ic"><IconSearch /></span>
          <input v-model="gq" class="input" placeholder="搜索组名 / 组长 / 成员" />
        </div>
        <button class="btn primary" @click="openCreate">+ 新建运营组</button>
      </div>
    </div>

    <div class="og-md">
      <div class="og-md-left">
        <template v-if="visibleGroups.length">
          <div
            v-for="{ group, leader, size } in visibleGroups"
            :key="group.id"
            class="og-md-item"
            :class="activeGroup?.id === group.id ? 'active' : ''"
            @click="selGroup = group.id"
          >
            <div class="og-md-item-hd">
              <span class="og-md-name">{{ group.name }}</span>
              <span class="og-g-count">{{ size }}人</span>
              <span class="og-md-more" @click.stop>
                <MoreActions :items="[
                  { label: '重命名', onClick: () => openEditGroup(group) },
                  { label: '删除组织', danger: true, onClick: () => deleteGroup(group) },
                ]">
                  <template #trigger><IconMore /></template>
                </MoreActions>
              </span>
            </div>
            <div class="og-md-item-sub">
              <span v-if="leader" class="og-lead-ava" :style="{ background: avaColor(leader.name) }">{{ leader.name.slice(0, 1) }}</span>
              组长：{{ leader?.name ?? '未指定' }}
            </div>
          </div>
        </template>
        <div v-else class="empty" :style="{ padding: '20px 0' }">无匹配运营组</div>
      </div>

      <div class="og-md-right">
        <div v-if="activeView && activeGroup" class="og-detail">
          <div class="og-detail-hd">
            <span class="og-g-name">{{ activeGroup.name }}</span>
          </div>
          <div class="og-detail-body">
            <div class="og-table">
              <div class="og-tr head">
                <div class="og-cell">成员名称</div>
                <div class="og-cell">职位</div>
                <div class="og-cell">添加时间</div>
                <div class="og-cell">添加人</div>
                <div class="og-cell">操作</div>
              </div>
              <div v-if="activeLeader" class="og-tr">
                <div class="og-cell og-td-name">
                  <span class="og-ava" :style="{ background: avaColor(activeLeader.name) }">{{ activeLeader.name.slice(0, 1) }}</span>
                  <span class="og-cell-nm">{{ activeLeader.name }}</span>
                </div>
                <div class="og-cell"><span class="og-role-tag" :style="roleTagStyle('leader')">{{ OPS_ROLE_LABEL['leader'] }}</span></div>
                <div class="og-cell og-td-dim">{{ activeLeader.addedAt }}</div>
                <div class="og-cell og-td-dim">{{ activeLeader.addedBy }}</div>
                <div class="og-cell">
                  <OgActionStack :items="[
                    { label: '转交组长', onClick: openLeaderTransfer },
                    { label: '添加专员', onClick: openLeaderAddSpec },
                  ]" />
                </div>
              </div>
              <div v-else class="og-tr-empty">该组暂无组长</div>
              <template v-for="sp in activeSpecs" :key="sp.memberId">
                <div class="og-tr spec" @click="toggleSpec(sp.memberId)">
                  <div class="og-cell og-td-name d1">
                    <span class="arrow" :class="(expSpecs.has(sp.memberId) ? 'open' : '') + ' ' + (assisOf(sp).length ? '' : 'leaf')"><IconArrow /></span>
                    <span class="og-ava" :style="{ background: avaColor(sp.name) }">{{ sp.name.slice(0, 1) }}</span>
                    <span class="og-cell-nm">{{ sp.name }}</span>
                    <span v-if="assisOf(sp).length > 0" class="og-g-count">{{ assisOf(sp).length }}助理</span>
                  </div>
                  <div class="og-cell"><span class="og-role-tag" :style="roleTagStyle('specialist')">{{ OPS_ROLE_LABEL['specialist'] }}</span></div>
                  <div class="og-cell og-td-dim">{{ sp.addedAt }}</div>
                  <div class="og-cell og-td-dim">{{ sp.addedBy }}</div>
                  <div class="og-cell" @click.stop>
                    <OgActionStack :items="[
                      { label: '转交专员', onClick: () => openTransfer(sp, activeGroup) },
                      { label: '添加助理', onClick: () => openAddSub('assistant', sp.memberId, activeGroup) },
                    ]" />
                  </div>
                </div>
                <template v-if="expSpecs.has(sp.memberId)">
                  <template v-if="assisOf(sp).length">
                    <div v-for="a in assisOf(sp)" :key="a.memberId" class="og-tr sub">
                      <div class="og-cell og-td-name d2">
                        <span class="arrow leaf"><IconArrow /></span>
                        <span class="og-ava sm" :style="{ background: avaColor(a.name) }">{{ a.name.slice(0, 1) }}</span>
                        <span class="og-cell-nm">{{ a.name }}</span>
                      </div>
                      <div class="og-cell"><span class="og-role-tag" :style="roleTagStyle('assistant')">{{ OPS_ROLE_LABEL['assistant'] }}</span></div>
                      <div class="og-cell og-td-dim">{{ a.addedAt }}</div>
                      <div class="og-cell og-td-dim">{{ a.addedBy }}</div>
                      <div class="og-cell og-td-dim">-</div>
                    </div>
                  </template>
                  <div v-else class="og-tr sub">
                    <div class="og-cell og-td-name d2">
                      <span class="arrow leaf"><IconArrow /></span>
                      <span class="og-td-dim">暂无助理</span>
                    </div>
                    <div class="og-cell" />
                    <div class="og-cell" />
                    <div class="og-cell" />
                    <div class="og-cell" />
                  </div>
                </template>
              </template>
              <div v-if="activeLeader && activeSpecs.length === 0" class="og-tr-empty">暂无专员，可在组长行「添加专员」</div>
            </div>
          </div>
        </div>
        <div v-else class="empty" :style="{ padding: '60px 0' }">请选择左侧运营组</div>
      </div>
    </div>
  </div>

  <!-- 弹窗 -->
  <OgCreateStep1Modal
    v-if="modal?.kind === 'createGroup' && modal.step === 1"
    :channel-label="channelLabel"
    @next="step2Next"
    @close="closeModal"
  />
  <OgCreateStep2Modal
    v-else-if="modal?.kind === 'createGroup' && modal.step === 2"
    :name="modal.name"
    :channel-label="channelLabel"
    :taken="takenIds"
    @confirm="step2Confirm"
    @back="step2BackCur"
    @close="closeModal"
  />
  <OgEditGroupModal
    v-else-if="modal?.kind === 'editGroup'"
    :group="modal.group"
    @confirm="editGroupConfirm"
    @close="closeModal"
  />
  <OgAddSubModal
    v-else-if="modal?.kind === 'addSub'"
    :role="modal.role"
    :group="modal.group"
    :parent-id="modal.parentId"
    :channel-members="channelMembers"
    :taken="takenIds"
    @confirm="addSubConfirm"
    @close="closeModal"
  />
  <OgTransferModal
    v-else-if="modal?.kind === 'transfer' && modal.entry.role === 'assistant'"
    :entry="modal.entry"
    :group="modal.group"
    :channel-groups="channelGroups"
    :channel-members="channelMembers"
    @confirm="transferConfirm"
    @close="closeModal"
  />
  <OgTransferPersonModal
    v-else-if="modal?.kind === 'transfer'"
    :entry="modal.entry"
    :group="modal.group"
    :role="modal.entry.role === 'leader' ? 'leader' : 'specialist'"
    :taken="takenIds"
    @confirm="transferPersonConfirm"
    @close="closeModal"
  />
  <Modal v-else-if="modal?.kind === 'confirm'" :title="modal.title" @close="closeModal">
    <div :style="{ display: 'flex', gap: '12px', alignItems: 'flex-start' }">
      <span :style="{ color: 'var(--danger)', flexShrink: 0 }"><IconWarn /></span>
      <div :style="{ color: 'var(--text-2)', lineHeight: 1.6, paddingTop: '1px' }">
        {{ modal.msg.pre }}<b>{{ modal.msg.bold }}</b>{{ modal.msg.post }}
      </div>
    </div>
    <template #foot>
      <button class="btn" @click="closeModal">取消</button>
      <button class="btn danger" @click="okConfirm(modal)">{{ modal.okText }}</button>
    </template>
  </Modal>

  <ToastWrap />
</template>
