// src/components/MoreActions.vue
<script lang="ts">
export interface MoreActionItem {
  label: string;
  /** 危险操作（红色） */
  danger?: boolean;
  onClick: () => void;
}
</script>

<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue';

defineProps<{ items: MoreActionItem[] }>();

const pos = ref<{ x: number; y: number } | null>(null);

const close = () => { pos.value = null; };
const onDocDown = () => close();

const openAt = (el: HTMLElement) => {
  const r = el.getBoundingClientRect();
  pos.value = { x: Math.max(8, Math.min(r.left, window.innerWidth - 130)), y: r.bottom + 6 };
  document.addEventListener('mousedown', onDocDown);
};

const pick = (it: MoreActionItem) => {
  close();
  document.removeEventListener('mousedown', onDocDown);
  it.onClick();
};

onBeforeUnmount(() => document.removeEventListener('mousedown', onDocDown));
</script>

<template>
  <!-- 操作列全局规范：最多直出两个操作，超出项收进「更多」，点击气泡展开。
       trigger：可选自定义触发器（如「⋯」图标），不传时默认渲染「更多」文字链接。 -->
  <span
    v-if="$slots.trigger"
    style="display: inline-flex; cursor: pointer"
    @click.prevent.stop="openAt(($event.currentTarget as HTMLElement))"
  >
    <slot name="trigger" />
  </span>
  <a v-else href="#" @click.prevent.stop="openAt(($event.currentTarget as HTMLElement))">更多</a>
  <Teleport to="body">
    <div v-if="pos" class="add-pop" :style="{ left: `${pos.x}px`, top: `${pos.y}px` }" @mousedown.stop>
      <div
        v-for="it in items"
        :key="it.label"
        class="add-pop-item"
        :class="{ danger: it.danger }"
        @click="pick(it)"
      >
        {{ it.label }}
      </div>
    </div>
  </Teleport>
</template>

// src/components/MoreActions.tsx
import { useEffect, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';

export interface MoreActionItem {
  label: string;
  /** 危险操作（红色） */
  danger?: boolean;
  onClick: () => void;
}

/**
 * 操作列全局规范：最多直出两个操作，超出项收进「更多」，点击气泡展开。
 * trigger：可选自定义触发器（如「⋯」图标），不传时默认渲染「更多」文字链接。
 */
export default function MoreActions({ items, trigger }: { items: MoreActionItem[]; trigger?: ReactNode }) {
  const [pos, setPos] = useState<{ x: number; y: number } | null>(null);

  useEffect(() => {
    if (!pos) return;
    const close = () => setPos(null);
    document.addEventListener('mousedown', close);
    return () => document.removeEventListener('mousedown', close);
  }, [pos]);

  const openAt = (el: HTMLElement) => {
    const r = el.getBoundingClientRect();
    setPos({ x: Math.max(8, Math.min(r.left, window.innerWidth - 130)), y: r.bottom + 6 });
  };

  return (
    <>
      {trigger !== undefined ? (
        <span
          style={{ display: 'inline-flex', cursor: 'pointer' }}
          onClick={(e) => {
            e.preventDefault();
            e.stopPropagation();
            openAt(e.currentTarget);
          }}
        >
          {trigger}
        </span>
      ) : (
        <a
          href="#"
          onClick={(e) => {
            e.preventDefault();
            e.stopPropagation();
            openAt(e.currentTarget);
          }}
        >
          更多
        </a>
      )}
      {pos &&
        createPortal(
          <div className="add-pop" style={{ left: pos.x, top: pos.y }} onMouseDown={(e) => e.stopPropagation()}>
            {items.map((it) => (
              <div
                className={`add-pop-item${it.danger ? ' danger' : ''}`}
                key={it.label}
                onClick={() => {
                  setPos(null);
                  it.onClick();
                }}
              >
                {it.label}
              </div>
            ))}
          </div>,
          document.body,
        )}
    </>
  );
}
