// src/components/Sidebar.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import type { MenuItem } from '../config/navigation';
import SidebarItem from './SidebarItem.vue';
import './Sidebar.css';

const props = defineProps<{
  menus: MenuItem[];
  activeKey: string;
  onSelect: (key: string) => void;
  className?: string;
}>();

/** 查找目标菜单项的父级 key（用于自动展开所在分组） */
function findParentKey(menus: MenuItem[], targetKey: string): string | undefined {
  for (const item of menus) {
    if (item.children?.some((child) => child.key === targetKey)) return item.key;
    if (item.children) {
      const found = findParentKey(item.children, targetKey);
      if (found) return found;
    }
  }
  return undefined;
}

const expandedKeys = ref<string[]>([]);

// 选中项变化时（如切换 Tab），自动展开其所在的分组
watch(
  () => [props.menus, props.activeKey] as const,
  ([menus, activeKey]) => {
    const parentKey = findParentKey(menus, activeKey);
    if (parentKey && !expandedKeys.value.includes(parentKey)) {
      expandedKeys.value = [...expandedKeys.value, parentKey];
    }
  },
  { immediate: true },
);

const toggleExpand = (key: string) => {
  expandedKeys.value = expandedKeys.value.includes(key)
    ? expandedKeys.value.filter((k) => k !== key)
    : [...expandedKeys.value, key];
};
</script>

<script lang="ts">
import type { MenuItem as _MenuItem } from '../config/navigation';

/** 深度优先查找第一个叶子菜单项（供外部 import） */
export function findFirstLeaf(menus: _MenuItem[]): _MenuItem | undefined {
  for (const item of menus) {
    if (!item.children?.length) return item;
    const leaf = findFirstLeaf(item.children);
    if (leaf) return leaf;
  }
  return undefined;
}
</script>

<template>
  <aside class="sidebar" :class="className ?? ''">
    <nav class="sidebar-menu">
      <SidebarItem
        v-for="item in menus"
        :key="item.key"
        :item="item"
        :depth="0"
        :active-key="activeKey"
        :expanded-keys="expandedKeys"
        @toggle="toggleExpand"
        @select="onSelect"
      />
    </nav>
  </aside>
</template>

// src/components/Sidebar.tsx
import { useEffect, useState, type ReactNode } from 'react';
import type { MenuItem } from '../config/navigation';
import './Sidebar.css';

interface SidebarProps {
  menus: MenuItem[];
  activeKey: string;
  onSelect: (key: string) => void;
}

/** 深度优先查找第一个叶子菜单项（用于 Tab 切换后的默认选中） */
export function findFirstLeaf(menus: MenuItem[]): MenuItem | undefined {
  for (const item of menus) {
    if (!item.children?.length) return item;
    const leaf = findFirstLeaf(item.children);
    if (leaf) return leaf;
  }
  return undefined;
}

/** 查找目标菜单项的父级 key（用于自动展开所在分组） */
function findParentKey(menus: MenuItem[], targetKey: string): string | undefined {
  for (const item of menus) {
    if (item.children?.some((child) => child.key === targetKey)) return item.key;
    if (item.children) {
      const found = findParentKey(item.children, targetKey);
      if (found) return found;
    }
  }
  return undefined;
}

export default function Sidebar({ menus, activeKey, onSelect }: SidebarProps) {
  const [expandedKeys, setExpandedKeys] = useState<string[]>([]);

  // 选中项变化时（如切换 Tab），自动展开其所在的分组
  useEffect(() => {
    const parentKey = findParentKey(menus, activeKey);
    if (parentKey) {
      setExpandedKeys((keys) =>
        keys.includes(parentKey) ? keys : [...keys, parentKey],
      );
    }
  }, [menus, activeKey]);

  const toggleExpand = (key: string) => {
    setExpandedKeys((keys) =>
      keys.includes(key) ? keys.filter((k) => k !== key) : [...keys, key],
    );
  };

  const renderMenuItem = (item: MenuItem, depth = 0): ReactNode => {
    const hasChildren = Boolean(item.children?.length);
    const isExpanded = expandedKeys.includes(item.key);
    const isActive = item.key === activeKey;

    return (
      <div key={item.key}>
        <button
          type="button"
          className={[
            'sidebar-item',
            isActive ? 'is-active' : '',
            depth > 0 ? 'is-child' : '',
          ]
            .filter(Boolean)
            .join(' ')}
          onClick={() => (hasChildren ? toggleExpand(item.key) : onSelect(item.key))}
        >
          <span className="sidebar-item-label">{item.label}</span>
          {hasChildren && (
            <span className={`sidebar-item-arrow ${isExpanded ? 'is-open' : ''}`}>
              ▾
            </span>
          )}
        </button>
        {hasChildren && isExpanded && (
          <div className="sidebar-submenu">
            {item.children!.map((child) => renderMenuItem(child, depth + 1))}
          </div>
        )}
      </div>
    );
  };

  return (
    <aside className="sidebar">
      <nav className="sidebar-menu">{menus.map((item) => renderMenuItem(item))}</nav>
    </aside>
  );
}
