// src/components/TopTabs.vue
<script setup lang="ts">
import type { TabConfig } from '../config/navigation';
import '../components/TopTabs.css';

defineProps<{
  tabs: TabConfig[];
  activeKey: string;
  onChange: (key: string) => void;
}>();
</script>

<template>
  <div class="top-tabs">
    <button
      v-for="tab in tabs"
      :key="tab.key"
      type="button"
      class="top-tabs-item"
      :class="{ 'is-active': tab.key === activeKey }"
      @click="onChange(tab.key)"
    >
      {{ tab.label }}
    </button>
  </div>
</template>

// src/components/TopTabs.tsx
import type { TabConfig } from '../config/navigation';
import './TopTabs.css';

interface TopTabsProps {
  tabs: TabConfig[];
  activeKey: string;
  onChange: (key: string) => void;
}

export default function TopTabs({ tabs, activeKey, onChange }: TopTabsProps) {
  return (
    <div className="top-tabs">
      {tabs.map((tab) => (
        <button
          key={tab.key}
          type="button"
          className={`top-tabs-item ${tab.key === activeKey ? 'is-active' : ''}`}
          onClick={() => onChange(tab.key)}
        >
          {tab.label}
        </button>
      ))}
    </div>
  );
}
