// src/pages/ops-center/OpsCenter.tsx
import { useState } from 'react';
import './OpsCenter.css';
import DashboardPage from './DashboardPage';
import InternalPage from './InternalPage';
import MarketPage from './MarketPage';
import SearchPage from './SearchPage';
import OperationManagePage from './OperationManagePage';
import ShopGoodsPage from './ShopGoodsPage';
import CreateProductPage from './CreateProductPage';
import TaskCenterPage from './TaskCenterPage';
import AiAssistantPage from './AiAssistantPage';
import MemberManagement from '../permission/MemberManagement';
import DepartmentManagement from '../permission/DepartmentManagement';
import RolePermission from '../permission/RolePermission';
import OpsGroupManagement from '../permission/OpsGroupManagement';

type PageKey =
  | 'dashboard'
  | 'internal'
  | 'market'
  | 'search'
  | 'operationManage'
  | 'shopGoods'
  | 'createTaobao'
  | 'createVideo'
  | 'taskCenter'
  | 'permMember'
  | 'permDept'
  | 'permRole'
  | 'permOpsGroup'
  | 'aiAssistant';

/** 智能运营中心外壳：侧边栏 + 顶栏 + 页面切换（与 preview.html 行为一致） */
export default function OpsCenter({ sidebarCollapsed, onToggleSidebar }: {
  sidebarCollapsed: boolean;
  onToggleSidebar: () => void;
}) {
  /* 默认展示内部商机（原版末尾 showPage('internal')） */
  const [page, setPage] = useState<PageKey>('internal');
  /* 高亮：顶栏 nav 与子级 subnav 共用，全局唯一 */
  const [active, setActive] = useState<string>('internal');
  /* 三组可展开菜单的展开状态（商机中心默认展开） */
  const [productOpen, setProductOpen] = useState(true);
  const [createOpen, setCreateOpen] = useState(false);
  const [permissionOpen, setPermissionOpen] = useState(false);

  /* 切到商品创建子页时自动展开菜单（原版 showCreateTaobao / showCreateVideo） */
  const showCreate = (key: 'createTaobao' | 'createVideo') => {
    setPage(key);
    setCreateOpen(true);
  };

  const onSubnav = (key: string, target?: PageKey) => {
    setActive(key);
    if (target) setPage(target);
  };

  const navCls = (key: PageKey) => `nav ${active === key ? 'active' : ''}`;
  const pageCls = (key: PageKey) => `page ${page === key ? 'show' : ''}`;

  return (
    <div className={`ops-center app ${sidebarCollapsed ? 'side-collapsed' : ''}`}>
      <div className="ops-topbar">
        <div className="ops-brand">
          <img className="ops-brand-logo" src="/logos/ops-logo.png" alt="" />
          <span className="ops-brand-name">智能运营中心</span>
        </div>
        <button
          type="button"
          className={`ops-side-toggle ${sidebarCollapsed ? 'is-collapsed' : ''}`}
          onClick={onToggleSidebar}
          title={sidebarCollapsed ? '展开侧边栏' : '收起侧边栏'}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2">
            <path d="M15 6l-6 6 6 6" />
          </svg>
        </button>
        <div className="ops-topbar-right">
          <button className="ops-bell" title="通知">🔔</button>
          <span className="ops-avatar">管</span>
        </div>
      </div>
      <div className="ops-body">
      <aside className={`side ${sidebarCollapsed ? 'collapsed' : ''}`}>
        <div className="side-scroll">
        <div className={navCls('dashboard')} onClick={() => onSubnav('dashboard', 'dashboard')}>
          <span className="nav-ico">▦</span>
          <span className="nav-text">运营驾驶舱</span>
        </div>
        <div className={navCls('operationManage')} onClick={() => onSubnav('operationManage', 'operationManage')}>
          <span className="nav-ico">◫</span>
          <span className="nav-text">运营管理</span>
        </div>
        <div
          className={`nav nav-parent ${productOpen ? 'open' : ''}`}
          onClick={(e) => {
            e.stopPropagation();
            setProductOpen((v) => !v);
          }}
        >
          <div className="nav-left">
            <span className="nav-ico">▣</span>
            <span className="nav-text">商机中心</span>
          </div>
          <span className="nav-arrow">▶</span>
        </div>
        <div className={`subnav-wrap ${productOpen ? 'show' : ''}`}>
          <div
            className={`subnav ${active === 'search' ? 'active' : ''}`}
            onClick={(e) => {
              e.stopPropagation();
              onSubnav('search', 'search');
            }}
          >
            全网搜索
          </div>
          <div
            className={`subnav ${active === 'internal' ? 'active' : ''}`}
            onClick={(e) => {
              e.stopPropagation();
              onSubnav('internal', 'internal');
            }}
          >
            内部商机
          </div>
          <div
            className={`subnav ${active === 'market' ? 'active' : ''}`}
            onClick={(e) => {
              e.stopPropagation();
              onSubnav('market', 'market');
            }}
          >
            市场商机
          </div>
        </div>
        <div className={navCls('shopGoods')} onClick={() => onSubnav('shopGoods', 'shopGoods')}>
          <span className="nav-ico">▥</span>
          <span className="nav-text">店铺商品</span>
        </div>
        <div
          className={`nav nav-parent ${createOpen ? 'open' : ''}`}
          onClick={(e) => {
            e.stopPropagation();
            setCreateOpen((v) => !v);
          }}
        >
          <div className="nav-left">
            <span className="nav-ico">✚</span>
            <span className="nav-text">商品创建</span>
          </div>
          <span className="nav-arrow">▶</span>
        </div>
        <div className={`subnav-wrap ${createOpen ? 'show' : ''}`}>
          <div
            className={`subnav ${active === 'createTaobao' ? 'active' : ''}`}
            onClick={(e) => {
              e.stopPropagation();
              setActive('createTaobao');
              showCreate('createTaobao');
            }}
          >
            淘宝
          </div>
          <div
            className={`subnav ${active === 'createVideo' ? 'active' : ''}`}
            onClick={(e) => {
              e.stopPropagation();
              setActive('createVideo');
              showCreate('createVideo');
            }}
          >
            视频号
          </div>
        </div>
        <div className={navCls('taskCenter')} onClick={() => onSubnav('taskCenter', 'taskCenter')}>
          <span className="nav-ico">▧</span>
          <span className="nav-text">任务中心</span>
        </div>
        <div className="nav">
          <span className="nav-ico">￥</span>
          <span className="nav-text">商品策略</span>
        </div>
        <div className={navCls('aiAssistant')} onClick={() => onSubnav('aiAssistant', 'aiAssistant')}>
          <span className="nav-ico">✦</span>
          <span className="nav-text">AI助手</span>
        </div>
        <div className="nav">
          <span className="nav-ico">⚙</span>
          <span className="nav-text">自动化中心</span>
        </div>
        <div
          className={`nav nav-parent ${permissionOpen ? 'open' : ''}`}
          onClick={(e) => {
            e.stopPropagation();
            setPermissionOpen((v) => !v);
          }}
        >
          <div className="nav-left">
            <span className="nav-ico">♟</span>
            <span className="nav-text">权限设置</span>
          </div>
          <span className="nav-arrow">▶</span>
        </div>
        <div className={`subnav-wrap ${permissionOpen ? 'show' : ''}`}>
          {(
            [
              { name: '店铺管理' },
              { name: '账号管理' },
              { name: '成员管理', target: 'permMember' },
              { name: '部门管理', target: 'permDept' },
              { name: '角色管理', target: 'permRole' },
              { name: '运营组管理', target: 'permOpsGroup' },
            ] as { name: string; target?: PageKey }[]
          ).map((item) => (
            <div
              key={item.name}
              className={`subnav ${active === item.name ? 'active' : ''}`}
              onClick={(e) => {
                e.stopPropagation();
                onSubnav(item.name, item.target);
              }}
            >
              {item.name}
            </div>
          ))}
        </div>
        </div>
        <div className="side-version">客户端 v1.0.1</div>
      </aside>

      <main className="main">
        <div className="content">
          <section className={pageCls('dashboard')}>
            <DashboardPage />
          </section>
          <section className={pageCls('internal')}>
            <InternalPage />
          </section>
          <section className={pageCls('market')}>
            <MarketPage />
          </section>
          <section className={pageCls('search')}>
            <SearchPage />
          </section>
          <section className={pageCls('operationManage')}>
            <OperationManagePage />
          </section>
          <section className={pageCls('shopGoods')}>
            <ShopGoodsPage />
          </section>
          <section className={pageCls('createTaobao')}>
            <CreateProductPage />
          </section>
          <section className={pageCls('createVideo')}>
            <CreateProductPage />
          </section>
          <section className={pageCls('aiAssistant')}>
            <AiAssistantPage />
          </section>
          <section className={pageCls('taskCenter')}>
            <TaskCenterPage />
          </section>
          <section className={pageCls('permMember')}>
            <div className="page-header">
              <div className="page-title">
                <p>组织成员 · 角色与账号状态</p>
              </div>
            </div>
            <div className="pm-page pm-embed">
              <MemberManagement />
            </div>
          </section>
          <section className={pageCls('permDept')}>
            <div className="page-header">
              <div className="page-title">
                <p>组织架构与部门成员</p>
              </div>
            </div>
            <div className="pm-page pm-embed">
              <DepartmentManagement />
            </div>
          </section>
          <section className={pageCls('permRole')}>
            <div className="page-header">
              <div className="page-title">
                <p>角色分组与功能权限配置</p>
              </div>
            </div>
            <div className="pm-page pm-embed">
              <RolePermission />
            </div>
          </section>
          <section className={pageCls('permOpsGroup')}>
            <div className="pm-page pm-embed">
              <OpsGroupManagement />
            </div>
          </section>
        </div>
      </main>
      </div>
    </div>
  );
}

// src/pages/ops-center/OpsCenter.vue
<script setup lang="ts">
import { ref } from 'vue';
import './OpsCenter.css';
import DashboardPage from './DashboardPage.vue';
import InternalPage from './InternalPage.vue';
import MarketPage from './MarketPage.vue';
import SearchPage from './SearchPage.vue';
import OperationManagePage from './OperationManagePage.vue';
import ShopGoodsPage from './ShopGoodsPage.vue';
import CreateProductPage from './CreateProductPage.vue';
import TaskCenterPage from './TaskCenterPage.vue';
import AiAssistantPage from './AiAssistantPage.vue';
import MemberManagement from '../permission/MemberManagement.vue';
import DepartmentManagement from '../permission/DepartmentManagement.vue';
import RolePermission from '../permission/RolePermission.vue';
import OpsGroupManagement from '../permission/OpsGroupManagement.vue';

type PageKey =
  | 'dashboard'
  | 'internal'
  | 'market'
  | 'search'
  | 'operationManage'
  | 'shopGoods'
  | 'createTaobao'
  | 'createVideo'
  | 'taskCenter'
  | 'permMember'
  | 'permDept'
  | 'permRole'
  | 'permOpsGroup'
  | 'aiAssistant';

/** 智能运营中心外壳：侧边栏 + 顶栏 + 页面切换（与 preview.html 行为一致） */
const props = defineProps<{ sidebarCollapsed: boolean }>();
const emit = defineEmits<{ (e: 'toggle'): void }>();

/* 默认展示内部商机（原版末尾 showPage('internal')） */
const page = ref<PageKey>('internal');
/* 高亮：顶栏 nav 与子级 subnav 共用，全局唯一 */
const active = ref<string>('internal');
/* 三组可展开菜单的展开状态（商机中心默认展开） */
const productOpen = ref(true);
const createOpen = ref(false);
const permissionOpen = ref(false);

/* 切到商品创建子页时自动展开菜单（原版 showCreateTaobao / showCreateVideo） */
const showCreate = (key: 'createTaobao' | 'createVideo') => {
  page.value = key;
  createOpen.value = true;
};

const onSubnav = (key: string, target?: PageKey) => {
  active.value = key;
  if (target) page.value = target;
};

/* 商品创建子项：高亮 + 切页 + 展开菜单（原版 setActive + showCreate） */
const clickCreate = (key: 'createTaobao' | 'createVideo') => {
  active.value = key;
  showCreate(key);
};

const navCls = (key: PageKey) => `nav ${active.value === key ? 'active' : ''}`;
const pageCls = (key: PageKey) => `page ${page.value === key ? 'show' : ''}`;

const permItems: { name: string; target?: PageKey }[] = [
  { name: '店铺管理' },
  { name: '账号管理' },
  { name: '成员管理', target: 'permMember' },
  { name: '部门管理', target: 'permDept' },
  { name: '角色管理', target: 'permRole' },
  { name: '运营组管理', target: 'permOpsGroup' },
];
</script>

<template>
  <div class="ops-center app" :class="sidebarCollapsed ? 'side-collapsed' : ''">
    <div class="ops-topbar">
      <div class="ops-brand">
        <img class="ops-brand-logo" src="/logos/ops-logo.png" alt="" />
        <span class="ops-brand-name">智能运营中心</span>
      </div>
      <button
        type="button"
        class="ops-side-toggle"
        :class="sidebarCollapsed ? 'is-collapsed' : ''"
        :title="sidebarCollapsed ? '展开侧边栏' : '收起侧边栏'"
        @click="emit('toggle')"
      >
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2">
          <path d="M15 6l-6 6 6 6" />
        </svg>
      </button>
      <div class="ops-topbar-right">
        <button class="ops-bell" title="通知">🔔</button>
        <span class="ops-avatar">管</span>
      </div>
    </div>
    <div class="ops-body">
      <aside class="side" :class="sidebarCollapsed ? 'collapsed' : ''">
        <div class="side-scroll">
          <div :class="navCls('dashboard')" @click="onSubnav('dashboard', 'dashboard')">
            <span class="nav-ico">▦</span>
            <span class="nav-text">运营驾驶舱</span>
          </div>
          <div :class="navCls('operationManage')" @click="onSubnav('operationManage', 'operationManage')">
            <span class="nav-ico">◫</span>
            <span class="nav-text">运营管理</span>
          </div>
          <div class="nav nav-parent" :class="productOpen ? 'open' : ''" @click.stop="productOpen = !productOpen">
            <div class="nav-left">
              <span class="nav-ico">▣</span>
              <span class="nav-text">商机中心</span>
            </div>
            <span class="nav-arrow">▶</span>
          </div>
          <div class="subnav-wrap" :class="productOpen ? 'show' : ''">
            <div class="subnav" :class="active === 'search' ? 'active' : ''" @click.stop="onSubnav('search', 'search')">
              全网搜索
            </div>
            <div class="subnav" :class="active === 'internal' ? 'active' : ''" @click.stop="onSubnav('internal', 'internal')">
              内部商机
            </div>
            <div class="subnav" :class="active === 'market' ? 'active' : ''" @click.stop="onSubnav('market', 'market')">
              市场商机
            </div>
          </div>
          <div :class="navCls('shopGoods')" @click="onSubnav('shopGoods', 'shopGoods')">
            <span class="nav-ico">▥</span>
            <span class="nav-text">店铺商品</span>
          </div>
          <div class="nav nav-parent" :class="createOpen ? 'open' : ''" @click.stop="createOpen = !createOpen">
            <div class="nav-left">
              <span class="nav-ico">✚</span>
              <span class="nav-text">商品创建</span>
            </div>
            <span class="nav-arrow">▶</span>
          </div>
          <div class="subnav-wrap" :class="createOpen ? 'show' : ''">
            <div
              class="subnav"
              :class="active === 'createTaobao' ? 'active' : ''"
              @click.stop="clickCreate('createTaobao')"
            >
              淘宝
            </div>
            <div
              class="subnav"
              :class="active === 'createVideo' ? 'active' : ''"
              @click.stop="clickCreate('createVideo')"
            >
              视频号
            </div>
          </div>
          <div :class="navCls('taskCenter')" @click="onSubnav('taskCenter', 'taskCenter')">
            <span class="nav-ico">▧</span>
            <span class="nav-text">任务中心</span>
          </div>
          <div class="nav">
            <span class="nav-ico">￥</span>
            <span class="nav-text">商品策略</span>
          </div>
          <div :class="navCls('aiAssistant')" @click="onSubnav('aiAssistant', 'aiAssistant')">
            <span class="nav-ico">✦</span>
            <span class="nav-text">AI助手</span>
          </div>
          <div class="nav">
            <span class="nav-ico">⚙</span>
            <span class="nav-text">自动化中心</span>
          </div>
          <div class="nav nav-parent" :class="permissionOpen ? 'open' : ''" @click.stop="permissionOpen = !permissionOpen">
            <div class="nav-left">
              <span class="nav-ico">♟</span>
              <span class="nav-text">权限设置</span>
            </div>
            <span class="nav-arrow">▶</span>
          </div>
          <div class="subnav-wrap" :class="permissionOpen ? 'show' : ''">
            <div
              v-for="item in permItems"
              :key="item.name"
              class="subnav"
              :class="active === item.name ? 'active' : ''"
              @click.stop="onSubnav(item.name, item.target)"
            >
              {{ item.name }}
            </div>
          </div>
        </div>
        <div class="side-version">客户端 v1.0.1</div>
      </aside>

      <main class="main">
        <div class="content">
          <section :class="pageCls('dashboard')">
            <DashboardPage />
          </section>
          <section :class="pageCls('internal')">
            <InternalPage />
          </section>
          <section :class="pageCls('market')">
            <MarketPage />
          </section>
          <section :class="pageCls('search')">
            <SearchPage />
          </section>
          <section :class="pageCls('operationManage')">
            <OperationManagePage />
          </section>
          <section :class="pageCls('shopGoods')">
            <ShopGoodsPage />
          </section>
          <section :class="pageCls('createTaobao')">
            <CreateProductPage />
          </section>
          <section :class="pageCls('createVideo')">
            <CreateProductPage />
          </section>
          <section :class="pageCls('aiAssistant')">
            <AiAssistantPage />
          </section>
          <section :class="pageCls('taskCenter')">
            <TaskCenterPage />
          </section>
          <section :class="pageCls('permMember')">
            <div class="page-header">
              <div class="page-title">
                <p>组织成员 · 角色与账号状态</p>
              </div>
            </div>
            <div class="pm-page pm-embed">
              <MemberManagement />
            </div>
          </section>
          <section :class="pageCls('permDept')">
            <div class="pm-page pm-embed">
              <DepartmentManagement />
            </div>
          </section>
          <section :class="pageCls('permRole')">
            <div class="page-header">
              <div class="page-title">
                <p>角色分组与功能权限配置</p>
              </div>
            </div>
            <div class="pm-page pm-embed">
              <RolePermission />
            </div>
          </section>
          <section :class="pageCls('permOpsGroup')">
            <div class="pm-page pm-embed">
              <OpsGroupManagement />
            </div>
          </section>
        </div>
      </main>
    </div>
  </div>
</template>
