// src/pages/ops-center/ShopGoodsPage.tsx
import { useMemo, useState } from 'react';
import BubbleSelect from '../../components/BubbleSelect';
import Ellipsis from '../../components/Ellipsis';
import { Modal, ToastWrap, useToasts } from '../permission/shared';
import { PLATFORM_LOGO } from './data';
import { sgProducts, sgDetail, SG_CHIPS, SG_STATUS_META } from './shopGoodsData';
import type { SgProduct } from './shopGoodsData';

type Tab = '视频号' | '淘宝' | '京喜' | '得物';

const copy = (text: string) => {
  navigator.clipboard?.writeText(text).catch(() => undefined);
};

/** 列表行操作：按商品状态给出 */
function rowActions(p: SgProduct): string[] {
  switch (p.status) {
    case 'selling':
    case 'auditFail':
      return ['商品详情', '下架'];
    case 'auditing':
      return ['商品详情', '撤销审核'];
    case 'offSystem':
    case 'offManual':
      return ['商品详情', '立即上架'];
    case 'draft':
      return ['商品详情', '发布'];
  }
}

/** 详情底部主操作：按商品状态给出 */
function footAction(p: SgProduct): { text: string; cls: string } {
  switch (p.status) {
    case 'selling':
    case 'auditFail':
      return { text: '下架', cls: 'warn' };
    case 'auditing':
      return { text: '撤销审核', cls: 'danger' };
    case 'offSystem':
    case 'offManual':
      return { text: '立即上架', cls: 'primary' };
    case 'draft':
      return { text: '发布上架', cls: 'primary' };
  }
}

/* ================= 批量调价 / 批量涨价弹窗 ================= */
type BpMode = 'adjust' | 'raise';
type BpMethod = 'rate' | 'profit';

/** 校验边界：利润 -5 ~ 999；利润率 -20% ~ 80% */
const BP_LIMIT: Record<BpMethod, { min: number; max: number }> = {
  rate: { min: -20, max: 80 },
  profit: { min: -5, max: 999 },
};

function BatchPriceModal({ count, onClose, onOk }: {
  count: number;
  onClose: () => void;
  onOk: (msg: string) => void;
}) {
  const [mode, setMode] = useState<BpMode>('adjust');
  const [method, setMethod] = useState<BpMethod>('rate');
  const [value, setValue] = useState('');
  const [err, setErr] = useState('');

  const modeText = mode === 'adjust' ? '批量调价' : '批量涨价';
  const methodLabel = mode === 'adjust' ? '调价方式' : '涨价方式';
  const limit = BP_LIMIT[method];

  const confirm = () => {
    const t = value.trim();
    if (!t) { setErr('请输入数值'); return; }
    const v = Number(t);
    if (!Number.isFinite(v)) { setErr('请输入有效数字'); return; }
    if (v < limit.min || v > limit.max) {
      setErr(
        method === 'rate'
          ? `利润率超出范围：最小 ${limit.min}%，最大 ${limit.max}%`
          : `利润超出范围：最小 ${limit.min}，最大 ${limit.max}`,
      );
      return;
    }
    onOk(`${modeText}成功：已对 ${count} 件出售中商品生效（${method === 'rate' ? `${t}%` : `${t} 元`}）`);
    onClose();
  };

  return (
    <Modal
      title={modeText}
      sub={`将对 ${count} 件出售中商品生效`}
      onClose={onClose}
      foot={
        <>
          <button className="btn" onClick={onClose}>取消</button>
          <button className="btn primary" onClick={confirm}>确定</button>
        </>
      }
    >
      <div className="bp-rows">
        <div className="bp-row">
          <span className="bp-label">模式</span>
          <div className="bp-opts">
            <span className={`bp-opt ${mode === 'adjust' ? 'on' : ''}`} onClick={() => { setMode('adjust'); setErr(''); }}>批量调价</span>
            <span className="bp-sep">/</span>
            <span className={`bp-opt ${mode === 'raise' ? 'on' : ''}`} onClick={() => { setMode('raise'); setErr(''); }}>批量涨价</span>
          </div>
        </div>
        <div className="bp-row">
          <span className="bp-label">{methodLabel}</span>
          <div className="bp-opts">
            <span className={`bp-opt ${method === 'rate' ? 'on' : ''}`} onClick={() => { setMethod('rate'); setErr(''); }}>
              {mode === 'adjust' ? '调整利润率' : '涨利润率'}
            </span>
            <span className="bp-sep">/</span>
            <span className={`bp-opt ${method === 'profit' ? 'on' : ''}`} onClick={() => { setMethod('profit'); setErr(''); }}>
              {mode === 'adjust' ? '调整利润' : '涨利润'}
            </span>
          </div>
        </div>
        <div className="bp-row">
          <span className="bp-label">{method === 'rate' ? '利润率' : '利润'}</span>
          <input
            className="sg-input bp-input"
            placeholder={method === 'rate' ? '如 8' : '如 5'}
            value={value}
            onChange={(e) => { setValue(e.target.value); setErr(''); }}
          />
          <span className="bp-unit">{method === 'rate' ? '%' : '元'}</span>
          <span className="bp-hint">{method === 'rate' ? '范围 -20% ~ 80%' : '范围 -5 ~ 999'}</span>
        </div>
        {err && <div className="bp-err">{err}</div>}
      </div>
    </Modal>
  );
}

export default function ShopGoodsPage() {
  const [tab, setTab] = useState<Tab>('视频号');
  const [chip, setChip] = useState('all');
  const [collapsed, setCollapsed] = useState(false);
  const [detail, setDetail] = useState<SgProduct | null>(null);
  /* 批量调价：勾选 + 弹窗 + toast */
  const [checked, setChecked] = useState<Set<string>>(new Set());
  const [bpOpen, setBpOpen] = useState(false);
  const { toasts, pushToast } = useToasts();

  /* 筛选 */
  const emptyFilter = { store: '', title: '', goodsId: '', sku: '', tpl: '', linkId: '', source: '全部来源', publisher: '', strategy: '全部策略' };
  const [filter, setFilter] = useState({ ...emptyFilter });
  const [applied, setApplied] = useState({ ...emptyFilter });

  const rows = useMemo(() => {
    const chipDef = SG_CHIPS.find((c) => c.key === chip) ?? SG_CHIPS[0];
    return sgProducts[tab].filter((p) => {
      if (!chipDef.match(p.status)) return false;
      if (applied.store && !p.store.includes(applied.store)) return false;
      if (applied.title && !p.title.includes(applied.title)) return false;
      if (applied.goodsId && !p.id.includes(applied.goodsId)) return false;
      if (applied.linkId && !p.linkId.includes(applied.linkId)) return false;
      if (applied.publisher && !p.publisher.includes(applied.publisher)) return false;
      if (applied.source !== '全部来源' && p.source !== applied.source) return false;
      if (applied.strategy !== '全部策略' && p.strategy !== applied.strategy) return false;
      return true;
    });
  }, [tab, chip, applied]);

  const countOf = (key: string) => {
    const def = SG_CHIPS.find((c) => c.key === key)!;
    return sgProducts[tab].filter((p) => def.match(p.status)).length;
  };

  /* 批量调价除淘宝外各 TAB 提供，且仅「销售中」状态商品可勾选调价 */
  const canPrice = tab !== '淘宝';
  const sellingSel = sgProducts[tab].filter((p) => checked.has(p.id) && p.status === 'selling').length;
  const sellRows = rows.filter((p) => p.status === 'selling');
  const allChecked = sellRows.length > 0 && sellRows.every((p) => checked.has(p.id));
  const toggleCheck = (id: string) => setChecked((prev) => {
    const n = new Set(prev);
    if (n.has(id)) n.delete(id); else n.add(id);
    return n;
  });
  const toggleAll = () => setChecked((prev) => {
    const n = new Set(prev);
    sellRows.forEach((p) => { if (allChecked) n.delete(p.id); else n.add(p.id); });
    return n;
  });

  if (detail) return <SgDetailPage product={detail} onBack={() => setDetail(null)} />;

  const fields = (
    <>
      <div className="sg-field">
        <label>店铺名</label>
        <input className="sg-input" placeholder="请输入店铺名" value={filter.store} onChange={(e) => setFilter({ ...filter, store: e.target.value })} />
      </div>
      <div className="sg-field">
        <label>商品名</label>
        <input className="sg-input" placeholder="请输入商品名" value={filter.title} onChange={(e) => setFilter({ ...filter, title: e.target.value })} />
      </div>
      <div className="sg-field">
        <label>商品ID</label>
        <input className="sg-input" placeholder="请输入商品ID" value={filter.goodsId} onChange={(e) => setFilter({ ...filter, goodsId: e.target.value })} />
      </div>
      <div className="sg-field">
        <label>SKU名称</label>
        <input className="sg-input" placeholder="请输入SKU名称" value={filter.sku} onChange={(e) => setFilter({ ...filter, sku: e.target.value })} />
      </div>
      {!collapsed && (
        <>
          <div className="sg-field">
            <label>模板号</label>
            <input className="sg-input" placeholder="请输入模板号" value={filter.tpl} onChange={(e) => setFilter({ ...filter, tpl: e.target.value })} />
          </div>
          <div className="sg-field">
            <label>链接商品ID</label>
            <input className="sg-input" placeholder="请输入链接商品ID" value={filter.linkId} onChange={(e) => setFilter({ ...filter, linkId: e.target.value })} />
          </div>
          <div className="sg-field">
            <label>发布商品来源</label>
            <BubbleSelect className="sg-select" value={filter.source} onChange={(v) => setFilter({ ...filter, source: v })} options={['全部来源', '链接商品库', '内部商机', '市场商机']} />
          </div>
          <div className="sg-field">
            <label>发布人</label>
            <input className="sg-input" placeholder="请输入发布人" value={filter.publisher} onChange={(e) => setFilter({ ...filter, publisher: e.target.value })} />
          </div>
          <div className="sg-field">
            <label>关联策略</label>
            <BubbleSelect className="sg-select" value={filter.strategy} onChange={(v) => setFilter({ ...filter, strategy: v })} options={['全部策略', '未关联', '默认发布策略', '高利润策略']} />
          </div>
          <div className="sg-field">
            <label>发布开始时间</label>
            <div className="sg-range">
              <input className="sg-input" placeholder="开始时间" />
              <span>→</span>
              <input className="sg-input" placeholder="结束时间" />
            </div>
          </div>
          <div className="sg-field">
            <label>上架开始时间</label>
            <div className="sg-range">
              <input className="sg-input" placeholder="开始时间" />
              <span>→</span>
              <input className="sg-input" placeholder="结束时间" />
            </div>
          </div>
        </>
      )}
    </>
  );

  return (
    <div className="sg-page">
      <div className="sg-tabs">
        {(['视频号', '淘宝', '京喜', '得物'] as Tab[]).map((t) => (
          <button key={t} className={`sg-tab ${tab === t ? 'active' : ''}`} onClick={() => { setTab(t); setChip('all'); setChecked(new Set()); }}>
            {t}
          </button>
        ))}
      </div>

      <div className="sg-statusbar">
        {SG_CHIPS.map((c) => (
          <button key={c.key} className={`sg-chip ${chip === c.key ? 'active' : ''}`} onClick={() => setChip(c.key)}>
            {c.label}({countOf(c.key)})
          </button>
        ))}
      </div>

      <div className="sg-filter">
        <div className="sg-grid">
          {fields}
          <div className="sg-actions">
            {canPrice && sellingSel > 0 && (
              <div className="sg-mini">已选 <b style={{ color: '#4f7cff' }}>{sellingSel}</b> 件出售中商品</div>
            )}
            {canPrice && (
              <button
                className="sg-btn primary"
                disabled={sellingSel === 0}
                title={sellingSel === 0 ? '请先勾选出售中的商品' : '对勾选的出售中商品批量调价'}
                onClick={() => setBpOpen(true)}
              >
                批量调价
              </button>
            )}
            <button className="sg-btn" onClick={() => setCollapsed((v) => !v)}>
              {collapsed ? '展开 ∨' : '收起 ∧'}
            </button>
            <button className="sg-btn" onClick={() => { setFilter({ ...emptyFilter }); setApplied({ ...emptyFilter }); }}>
              重置
            </button>
            <button className="sg-btn primary" onClick={() => setApplied({ ...filter })}>
              查询
            </button>
          </div>
        </div>
      </div>

      <div className="sg-card">
        <div style={{ overflow: 'auto' }}>
          <table className="sg-table">
            <thead>
              <tr>
                {canPrice && (
                  <th style={{ width: 44 }}><input type="checkbox" checked={allChecked} onChange={toggleAll} /></th>
                )}
                <th>商品信息</th>
                <th style={{ width: 130 }}>商品状态</th>
                <th style={{ width: 120 }}>商品策略</th>
                <th style={{ width: 130 }}>商品数据 ⇅</th>
                <th style={{ width: 240 }}>发布信息 ⇅</th>
                <th style={{ width: 110 }}>操作</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((p) => {
                const meta = SG_STATUS_META[p.status];
                return (
                  <tr key={p.id}>
                    {canPrice && (
                      <td>
                        {p.status === 'selling' && (
                          <input type="checkbox" checked={checked.has(p.id)} onChange={() => toggleCheck(p.id)} />
                        )}
                      </td>
                    )}
                    <td>
                      <div className="sg-goods">
                        <img className="sg-thumb" src={p.img} alt="" />
                        <div className="sg-ginfo">
                          <div className="sg-gtitle"><Ellipsis text={p.title} /></div>
                          <div className="sg-gid">
                            链接商品ID：<span>{p.linkId}</span>
                            <button className="sg-copy" title="复制" onClick={() => copy(p.linkId)}>⧉</button>
                          </div>
                          <div className="sg-gid">
                            商品ID：<span>{p.id}</span>
                            <button className="sg-copy" title="复制" onClick={() => copy(p.id)}>⧉</button>
                          </div>
                        </div>
                      </div>
                    </td>
                    <td>
                      <div className="sg-status">
                        <span className="sg-dot" style={{ background: meta.dot }} />
                        <span style={{ color: meta.color }}>{meta.label}</span>
                      </div>
                      {p.status === 'auditFail' && (
                        <div className="sg-failtag" title={p.rejectReason}>
                          审核未通过 <i className="sg-fail-i" title={p.rejectReason}>i</i>
                        </div>
                      )}
                    </td>
                    <td>{p.strategy}</td>
                    <td>
                      <div className="sg-kv">总销量：<b>{p.sales}</b></div>
                      <div className="sg-kv">评价数：<b>{p.reviews}</b></div>
                    </td>
                    <td>
                      <div className="sg-kv"><span className="sg-kv-l">发布人：</span><b>{p.publisher}</b></div>
                      <div className="sg-kv sg-kv-store">
                        <span className="sg-kv-l">发布店铺：</span>
                        <span className="store-logo"><img src={PLATFORM_LOGO[p.storePlatform]} alt="" /></span>
                        <b>{p.store}</b>
                      </div>
                      <div className="sg-kv"><span className="sg-kv-l">{p.shelfTime ? '上架时间：' : '发布时间：'}</span><b>{p.shelfTime ?? p.publishTime}</b></div>
                    </td>
                    <td>
                      <div className="sg-acts">
                        {rowActions(p).map((a) => (
                          <a
                            key={a}
                            className="sg-link"
                            href="javascript:void(0)"
                            onClick={(e) => { e.preventDefault(); if (a === '商品详情') setDetail(p); }}
                          >
                            {a}
                          </a>
                        ))}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          {rows.length === 0 && (
            <div className="sg-empty">
              <div className="sg-empty-wrap">
                <div className="sg-empty-icon">◌</div>
                <div>暂无数据，请调整筛选条件</div>
              </div>
            </div>
          )}
        </div>
      </div>

      <div className="pm-page pm-host">
        {bpOpen && sellingSel > 0 && (
          <BatchPriceModal count={sellingSel} onClose={() => setBpOpen(false)} onOk={pushToast} />
        )}
        <ToastWrap toasts={toasts} />
      </div>
    </div>
  );
}

/* ================= 详情页 ================= */

export function SgDetailPage({ product: p, onBack, foot: footProp, hideEdit }: {
  product: SgProduct;
  onBack: () => void;
  /** 覆盖底部主操作（不传按商品状态推断；内部商机等复用场景传入，支持多个按钮） */
  foot?: { text: string; cls: string }[];
  /** 隐藏右上「编辑」按钮（商机等不可编辑场景） */
  hideEdit?: boolean;
}) {
  const [specOpen, setSpecOpen] = useState(true);
  const [skuShow, setSkuShow] = useState(true);
  const foot = footProp ?? [footAction(p)];

  const statusTag =
    p.status === 'selling' ? { text: '出售中', cls: 'green' }
    : p.status === 'auditing' ? { text: '审核中', cls: 'blue' }
    : p.status === 'auditFail' ? { text: '审核未通过', cls: 'red' }
    : p.status === 'draft' ? { text: '草稿', cls: 'orange' }
    : { text: '已下架', cls: 'gray' };

  const thumbs = [p.img, ...sgDetail.mainImgs.slice(0, 4)];

  return (
    <div className="sg-page sgd-page">
      <div className="sgd-hero">
      <div className="sgd-top">
        <div className="sgd-top-left">
          <button className="sgd-back" onClick={onBack} title="返回">←</button>
          <span className="sgd-top-title">商品详情</span>
        </div>
        {!hideEdit && <button className="sg-btn">编辑</button>}
      </div>

      <div className="sgd-cat">
        <span className="sgd-cat-label">当前类目<i>*</i></span>
        <span>{p.category.join(' / ')}</span>
      </div>
      <div className="sgd-head">
        <div className="sgd-gallery">
          <div className="sgd-thumbs">
            {thumbs.map((t, i) => (
              <img key={i} className={`sgd-thumb ${i === 0 ? 'active' : ''}`} src={t} alt="" />
            ))}
          </div>
          <img className="sgd-main" src={p.img} alt="" />
        </div>
        <div className="sgd-info">
          <h2>{p.title}</h2>
          <div className="sgd-fields">
            <div className="sgd-frow"><span>商品来源：</span><b>{p.source}</b></div>
            <div className="sgd-frow"><span>版本号：</span><b>{p.version}</b></div>
            <div className="sgd-frow"><span>商品ID：</span><b>{p.id}</b></div>
            <div className="sgd-frow"><span>操作人：</span><b>{p.operator}</b></div>
            {p.status !== 'draft' && p.status !== 'auditing' && (
              <div className="sgd-frow">
                <span>上架店铺：</span>
                <b className="sgd-store">
                  <span className="store-logo"><img src={PLATFORM_LOGO[p.storePlatform]} alt="" /></span>
                  {p.store}
                </b>
              </div>
            )}
            {p.shelfTime && <div className="sgd-frow"><span>上架时间：</span><b>{p.shelfTime}</b></div>}
            {p.submitTime && <div className="sgd-frow"><span>提交审核时间：</span><b>{p.submitTime}</b></div>}
            {p.createTime && <div className="sgd-frow"><span>创建时间：</span><b>{p.createTime}</b></div>}
            {p.offTime && <div className="sgd-frow"><span>下架时间：</span><b>{p.offTime}</b></div>}
            {p.offReason && <div className="sgd-frow"><span>下架原因：</span><b className="sgd-red">{p.offReason}</b></div>}
            {p.rejectReason && <div className="sgd-frow"><span>驳回原因：</span><b className="sgd-red">{p.rejectReason}</b></div>}
            <div className="sgd-frow">
              <span>商品状态：</span>
              <b><span className={`sgd-tag ${statusTag.cls}`}>{statusTag.text}</span></b>
            </div>
            {p.status !== 'draft' && (
              <div className="sgd-frow"><span>商品策略：</span><b>{p.strategy}</b></div>
            )}
          </div>
        </div>
      </div>
      </div>

      <div className="sgd-sec">
        <div className="sgd-sec-head">
          <div className="sgd-sec-title">商品规格</div>
          <button className="sgd-collapse" onClick={() => setSpecOpen((v) => !v)}>{specOpen ? '∨ 收起' : '∧ 展开'}</button>
        </div>
        {specOpen && (
          <div className="sgd-sec-body">
            <div className="sgd-spec-row">
              <span className="sgd-spec-label">颜色</span>
              <div className="sgd-spec-chips">{sgDetail.colors.map((c) => <span key={c} className="sgd-chip">{c}</span>)}</div>
            </div>
            <div className="sgd-spec-row">
              <span className="sgd-spec-label">规格</span>
              <div className="sgd-spec-chips">{sgDetail.styles.map((c) => <span key={c} className="sgd-chip">{c}</span>)}</div>
            </div>
          </div>
        )}
      </div>

      <div className="sgd-sec">
        <div className="sgd-sec-head">
          <div className="sgd-sec-title">商品SKU</div>
          <label className="sgd-sku-toggle">
            <input type="checkbox" checked={skuShow} onChange={(e) => setSkuShow(e.target.checked)} />
            展开明细
          </label>
        </div>
        <div className="sgd-sec-body">
          {skuShow && (
            <table className="sg-table sgd-sku-table">
              <thead>
                <tr>
                  <th style={{ width: 76 }}>SKU图</th>
                  <th style={{ width: 76 }}>编码图片</th>
                  <th>颜色分类</th>
                  <th style={{ width: 120 }}>款式</th>
                  <th style={{ width: 160 }}>SKU名称</th>
                  <th style={{ width: 160 }}>商品编码</th>
                </tr>
              </thead>
              <tbody>
                {sgDetail.skus.map((s, i) => (
                  <tr key={i}>
                    <td><img className="sgd-sku-img" src={p.img} alt="" /></td>
                    <td><img className="sgd-sku-img" src={p.img} alt="" /></td>
                    <td>{i % 2 === 0 ? s.color : ''}</td>
                    <td>{s.style}</td>
                    <td>{s.name}</td>
                    <td><span className="sgd-code">{s.code}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
          <div className="sgd-price">
            <span>一口价<i>*</i></span>
            <input className="sg-input sgd-price-input" defaultValue={sgDetail.price} readOnly />
          </div>
        </div>
      </div>

      <div className="sgd-sec">
        <div className="sgd-sec-head"><div className="sgd-sec-title">3:4主图</div></div>
        <div className="sgd-sec-body">
          <div className="sgd-note">最多上传5张图片，支持最小尺寸750*1000，固定宽高比例为3:4，大小20M以内</div>
          <div className="sgd-imgs ratio34">{sgDetail.mainImgs.map((m, i) => <img key={i} src={m} alt="" />)}</div>
        </div>
      </div>

      <div className="sgd-sec">
        <div className="sgd-sec-head"><div className="sgd-sec-title">商品详情</div></div>
        <div className="sgd-sec-body">
          <div className="sgd-note">宝贝详情图【高度≤2】，超出将被裁剪，建议宽度≥1440像素以确保清晰，拖动模块可排序</div>
          <div className="sgd-imgs">{sgDetail.detailImgs.map((m, i) => <img key={i} src={m} alt="" />)}</div>
        </div>
      </div>

      <div className="sgd-sec">
        <div className="sgd-sec-head"><div className="sgd-sec-title">商品视频</div></div>
        <div className="sgd-sec-body">
          <div className="sgd-note">视频要求：时长5秒~5分钟；宽高比支持1:1、3:4、9:16（9:16视频商品详情页不展示，可在首页推荐、微详情等展示）最多可上传5个</div>
          <div className="sgd-imgs">
            {sgDetail.videos.map((m, i) => (
              <span key={i} className="sgd-video"><img src={m} alt="" /><i className="sgd-play">▶</i></span>
            ))}
          </div>
        </div>
      </div>

      <div className="sgd-sec">
        <div className="sgd-sec-head"><div className="sgd-sec-title">通用商品白底图</div></div>
        <div className="sgd-sec-body">
          <div className="sgd-note">宽高800*800，所报名商品台的白底图，纯白边，图片饱满（上下贴边或左右贴边），将作为个性化素材展示</div>
          <div className="sgd-imgs"><img src={sgDetail.whiteImg} alt="" /></div>
        </div>
      </div>

      <div className="sgd-sec">
        <div className="sgd-sec-head"><div className="sgd-sec-title">通用商品场景图(非必填)</div></div>
        <div className="sgd-sec-body">
          <div className="sgd-note">基本要求：带有背景，无牛皮癣，主体清晰完整不变形、不拼图、不含图、不留白边，建议主体突出与背景和谐。背景不宜过于复杂，色调自然。格式要求：800*800px，JPG/JPEG、小于3M</div>
          <div className="sgd-imgs"><img src={sgDetail.sceneImg} alt="" /></div>
        </div>
      </div>

      <div className="sgd-foot">
        {foot.map((f) => (
          <button key={f.text} className={`sgd-foot-btn ${f.cls}`}>{f.text}</button>
        ))}
      </div>
    </div>
  );
}

// src/pages/ops-center/ShopGoodsPage.vue
<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue';
import BubbleSelect from '../../components/BubbleSelect.vue';
import Ellipsis from '../../components/Ellipsis.vue';
import SortTh from '../../components/SortTh.vue';
import { pushToast } from '../../components/toast';
import { PLATFORM_LOGO } from './data';
import { sgProducts, SG_CHIPS, SG_STATUS_META, sgRowActions, SG_OFF_FAIL_TYPES, SG_OFF_GROUP, SG_OFF_GROUPS, sgWarnType } from './shopGoodsData';
import type { SgProduct, SgTab } from './shopGoodsData';
import SgDetailPage from './SgDetailPage.vue';
import JmCreateDetailPage from './JmCreateDetailPage.vue';
import SgBatchPriceModal from './SgBatchPriceModal.vue';
import CwRelDrawer from './CwRelDrawer.vue';

const copy = (text: string) => {
  navigator.clipboard?.writeText(text).catch(() => undefined);
};

/** 列表行操作：与运营管理操作列共用 sgRowActions，保持同步 */
const rowActions = (p: SgProduct) => sgRowActions(p.status);

const tab = ref<SgTab>('视频号');
const chip = ref('all');
/* 已下架 tab 下的下架类型筛选 */
const offType = ref('全部');
const onChip = (k: string) => { chip.value = k; offType.value = '全部'; };
const collapsed = ref(false);
const detail = ref<SgProduct | null>(null);
/* 风险预警：关联商品抽屉 */
const relTarget = ref<SgProduct | null>(null);
/* 京麦商品详情：走京麦接口字段页（SgProduct → CreateRow 适配，字段映射 getProduct/material） */
const jmDetailRow = computed(() => detail.value && detail.value.storePlatform === '京麦'
  ? { thumb: detail.value.img, title: detail.value.title, link: detail.value.linkId, store: detail.value.store, person: detail.value.operator, time: detail.value.createTime ?? detail.value.publishTime, platformBadge: '京麦' }
  : null);
/* 批量调价：勾选 + 弹窗 + toast */
const checked = ref<Set<string>>(new Set());
const bpOpen = ref(false);

/* 筛选 */
const emptyFilter = { store: '', title: '', goodsId: '', seriesCode: '', tpl: '', linkId: '', source: '全部来源', publisher: '', strategy: '全部策略', publishMode: '全部', hitWarn: '全部' };
const filter = ref({ ...emptyFilter });
const applied = ref({ ...emptyFilter });
const patchFilter = (patch: Partial<typeof emptyFilter>) => { filter.value = { ...filter.value, ...patch }; };

/* 消息通知跳转定位：收到令牌后回全部态并按商品ID自动查询 */
const props = defineProps<{ locate?: { id: string; ts: number } | null }>();
watch(() => props.locate, (v) => {
  if (!v) return;
  chip.value = 'all';
  filter.value = { ...emptyFilter, goodsId: v.id };
  applied.value = { ...filter.value };
});
/* 预警相关查询条件（发布方式/下架时间）展示状态：全部/销售中/已下架 */
const warnConds = computed(() => ['all', 'selling', 'off'].includes(chip.value));

const isFailOff = (p: SgProduct) => !!p.offType && SG_OFF_FAIL_TYPES.includes(p.offType);

const rows = computed(() => {
  const chipDef = SG_CHIPS.find((c) => c.key === chip.value) ?? SG_CHIPS[0];
  const list = sgProducts[tab.value].filter((p) => {
    if (!chipDef.match(p.status)) return false;
    if (chip.value === 'off' && offType.value !== '全部' && (!p.offType || SG_OFF_GROUP[p.offType] !== offType.value)) return false;
    if (applied.value.store && !p.store.includes(applied.value.store)) return false;
    if (applied.value.title && !p.title.includes(applied.value.title)) return false;
    if (applied.value.goodsId && !p.id.includes(applied.value.goodsId)) return false;
    if (applied.value.seriesCode && !p.seriesCode.includes(applied.value.seriesCode)) return false;
    if (applied.value.publishMode !== '全部' && p.publishMode !== applied.value.publishMode) return false;
    if (applied.value.hitWarn === '命中预警' && !sgWarnType(p)) return false;
    if (applied.value.hitWarn === '未命中预警' && sgWarnType(p)) return false;
    if (applied.value.linkId && !p.linkId.includes(applied.value.linkId)) return false;
    if (applied.value.publisher && !p.publisher.includes(applied.value.publisher)) return false;
    if (applied.value.source !== '全部来源' && p.source !== applied.value.source) return false;
    if (applied.value.strategy !== '全部策略' && p.strategy !== applied.value.strategy) return false;
    return true;
  });
  const k = sortKey.value;
  if (!k) return list;
  const val = (p: SgProduct): number | string => {
    if (k === 'sold') return numOf(p.sold30);
    const t = p.shelfTime ?? p.publishTime;
    return t === '-' ? '' : t;
  };
  return [...list].sort((a, b) => {
    const va = val(a);
    const vb = val(b);
    const d = typeof va === 'number' && typeof vb === 'number' ? va - vb : String(va).localeCompare(String(vb));
    return sortDir.value === 'desc' ? -d : d;
  });
});

/* 排序：单列激活，点击循环 降序→升序→取消 */
type SgSortKey = 'sold' | 'pub';
const sortKey = ref<SgSortKey | null>(null);
const sortDir = ref<'asc' | 'desc'>('desc');
const toggleSort = (k: SgSortKey) => {
  if (sortKey.value !== k) { sortKey.value = k; sortDir.value = 'desc'; }
  else if (sortDir.value === 'desc') sortDir.value = 'asc';
  else { sortKey.value = null; sortDir.value = 'desc'; }
};
const sortIco = (k: SgSortKey): 'none' | 'asc' | 'desc' => (sortKey.value === k ? sortDir.value : 'none');
const numOf = (s: string) => Number(s.replace(/,/g, '')) || 0;
/* 销量数据块：无数据展示 0（对齐微信小店经营概览） */
const zero = (v: string) => (v === '-' ? '0' : v);

/* 下架原因悬浮气泡：fixed 定位挂在页面层，不被表格容器裁剪、悬浮不抖动 */
const offPop = reactive({ show: false, x: 0, y: 0, text: '' });
const showOffPop = (e: MouseEvent, text: string) => {
  const r = (e.currentTarget as HTMLElement).getBoundingClientRect();
  const h = 76;
  offPop.text = text;
  offPop.x = r.left;
  offPop.y = r.bottom + 6 + h > window.innerHeight ? r.top - 6 - h : r.bottom + 6;
  offPop.show = true;
};
const hideOffPop = () => { offPop.show = false; };

const countOf = (key: string) => {
  const def = SG_CHIPS.find((c) => c.key === key)!;
  return sgProducts[tab.value].filter((p) => def.match(p.status)).length;
};

/* 批量调价除淘宝外各 TAB 提供，且仅「销售中」状态商品可勾选调价 */
const canPrice = computed(() => tab.value !== '淘宝');
const sellingSel = computed(() => sgProducts[tab.value].filter((p) => checked.value.has(p.id) && p.status === 'selling').length);
const sellRows = computed(() => rows.value.filter((p) => p.status === 'selling'));
const allChecked = computed(() => sellRows.value.length > 0 && sellRows.value.every((p) => checked.value.has(p.id)));
const toggleCheck = (id: string) => {
  const n = new Set(checked.value);
  if (n.has(id)) n.delete(id); else n.add(id);
  checked.value = n;
};
const toggleAll = () => {
  const n = new Set(checked.value);
  sellRows.value.forEach((p) => { if (allChecked.value) n.delete(p.id); else n.add(p.id); });
  checked.value = n;
};

const onTab = (t: SgTab) => { tab.value = t; chip.value = 'all'; offType.value = '全部'; checked.value = new Set(); };
</script>

<template>
  <JmCreateDetailPage v-if="detail && jmDetailRow" :row="jmDetailRow" @back="detail = null" @open-pub="pushToast('已关联发布任务')" />
  <SgDetailPage v-else-if="detail" :product="detail" @back="detail = null" />
  <div v-else class="sg-page">
    <div class="sg-tabs">
      <button v-for="t in (['视频号', '淘宝', '京喜', '得物', '京麦'] as SgTab[])" :key="t" class="sg-tab" :class="tab === t ? 'active' : ''" @click="onTab(t)">
        {{ t }}
      </button>
    </div>

    <div class="sg-statusbar">
      <button v-for="c in SG_CHIPS" :key="c.key" class="sg-chip" :class="chip === c.key ? 'active' : ''" @click="onChip(c.key)">
        {{ c.label }}({{ countOf(c.key) }})
      </button>
    </div>

    <div class="sg-filter">
      <div class="sg-grid">
        <div class="sg-field">
          <label>店铺名</label>
          <input class="sg-input" placeholder="请输入店铺名" :value="filter.store" @input="patchFilter({ store: ($event.target as HTMLInputElement).value })" />
        </div>
        <div class="sg-field">
          <label>商品名</label>
          <input class="sg-input" placeholder="请输入商品名" :value="filter.title" @input="patchFilter({ title: ($event.target as HTMLInputElement).value })" />
        </div>
        <div class="sg-field">
          <label>商品ID</label>
          <input class="sg-input" placeholder="请输入商品ID" :value="filter.goodsId" @input="patchFilter({ goodsId: ($event.target as HTMLInputElement).value })" />
        </div>
        <template v-if="!collapsed">
          <div class="sg-field">
            <label>系列编码</label>
            <input class="sg-input" placeholder="请输入系列编码" :value="filter.seriesCode" @input="patchFilter({ seriesCode: ($event.target as HTMLInputElement).value })" />
          </div>
          <div class="sg-field">
            <label>模板号</label>
            <input class="sg-input" placeholder="请输入模板号" :value="filter.tpl" @input="patchFilter({ tpl: ($event.target as HTMLInputElement).value })" />
          </div>
          <div class="sg-field">
            <label>链接商品ID</label>
            <input class="sg-input" placeholder="请输入链接商品ID" :value="filter.linkId" @input="patchFilter({ linkId: ($event.target as HTMLInputElement).value })" />
          </div>
          <div class="sg-field">
            <label>发布商品来源</label>
            <BubbleSelect class-name="sg-select" :value="filter.source" :options="['全部来源', '链接商品库', '内部商机', '市场商机']" @change="(v: string) => patchFilter({ source: v })" />
          </div>
          <div class="sg-field">
            <label>发布人</label>
            <input class="sg-input" placeholder="请输入发布人" :value="filter.publisher" @input="patchFilter({ publisher: ($event.target as HTMLInputElement).value })" />
          </div>
          <div class="sg-field">
            <label>关联策略</label>
            <BubbleSelect class-name="sg-select" :value="filter.strategy" :options="['全部策略', '未关联', '默认发布策略', '高利润策略']" @change="(v: string) => patchFilter({ strategy: v })" />
          </div>
          <div class="sg-field">
            <label>发布方式</label>
            <BubbleSelect class-name="sg-select" :value="filter.publishMode" :options="['全部', '蜂联', '店铺发布']" @change="(v: string) => patchFilter({ publishMode: v })" />
          </div>
          <div class="sg-field">
            <label>上架开始时间</label>
            <div class="sg-range">
              <input class="sg-input" placeholder="开始时间" />
              <span>→</span>
              <input class="sg-input" placeholder="结束时间" />
            </div>
          </div>
          <div v-if="chip === 'off'" class="sg-field">
            <label>下架类型</label>
            <BubbleSelect class-name="sg-select" :value="offType" :options="['全部', ...SG_OFF_GROUPS]" @change="(v: string) => offType = v" />
          </div>
          <div v-if="warnConds" class="sg-field">
            <label>下架时间</label>
            <div class="sg-range">
              <input class="sg-input" placeholder="开始时间" />
              <span>→</span>
              <input class="sg-input" placeholder="结束时间" />
            </div>
          </div>
          <!-- 销量 XX 日 大于/等于/小于 XXX：销量查询（与运营管理同款形式） -->
          <div class="sg-field">
            <label>销量</label>
            <div class="sg-compact">
              <input class="sg-input" placeholder="销量" />
              <span>日</span>
              <BubbleSelect class-name="sg-select" default-value="请选择" :options="['大于', '等于', '小于']" />
              <input class="sg-input" placeholder="请输入值" />
            </div>
          </div>
          <div class="sg-field">
            <label>是否命中预警</label>
            <BubbleSelect class-name="sg-select" :value="filter.hitWarn" :options="['全部', '命中预警', '未命中预警']" @change="(v: string) => patchFilter({ hitWarn: v })" />
          </div>
        </template>
        <div class="sg-actions">
          <div v-if="canPrice && sellingSel > 0" class="sg-mini">已选 <b>{{ sellingSel }}</b> 件出售中商品</div>
          <button
            v-if="canPrice"
            class="sg-btn primary"
            :disabled="sellingSel === 0"
            :title="sellingSel === 0 ? '请先勾选出售中的商品' : '对勾选的出售中商品批量调价'"
            @click="bpOpen = true"
          >
            批量调价
          </button>
          <button class="sg-btn" @click="collapsed = !collapsed">
            {{ collapsed ? '展开 ∨' : '收起 ∧' }}
          </button>
          <button class="sg-btn" @click="filter = { ...emptyFilter }; applied = { ...emptyFilter }">
            重置
          </button>
          <button class="sg-btn primary" @click="applied = { ...filter }">
            查询
          </button>
        </div>
      </div>
    </div>

    <div class="sg-card">
      <div :style="{ overflow: 'auto' }">
        <table class="sg-table">
          <thead>
            <tr>
              <th v-if="canPrice" :style="{ width: '44px' }"><input type="checkbox" :checked="allChecked" @change="toggleAll" /></th>
              <th :style="{ width: '380px' }">商品信息</th>
              <SortTh label="近20日销量概览" width="140px" :state="sortIco('sold')" @sort="toggleSort('sold')" />
              <th :style="{ width: '150px' }">商品状态</th>
              <th :style="{ width: '120px' }">商品策略</th>
              <th :style="{ width: '150px' }">预警</th>
              <SortTh label="发布信息" width="240px" :state="sortIco('pub')" @sort="toggleSort('pub')" />
              <th :style="{ width: '110px' }">操作</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="p in rows" :key="p.id">
              <td v-if="canPrice">
                <input v-if="p.status === 'selling'" type="checkbox" :checked="checked.has(p.id)" @change="toggleCheck(p.id)" />
              </td>
              <td>
                <div class="sg-goods">
                  <img class="sg-thumb" :src="p.img" alt="" />
                  <div class="sg-ginfo">
                    <div class="sg-gtitle"><Ellipsis :text="p.title" /></div>
                    <div class="sg-gid">
                      链接商品ID：<span>{{ p.linkId }}</span>
                      <button class="sg-copy" title="复制" @click="copy(p.linkId)">⧉</button>
                    </div>
                    <div class="sg-gid">
                      商品ID：<span>{{ p.id }}</span>
                      <button class="sg-copy" title="复制" @click="copy(p.id)">⧉</button>
                    </div>
                  </div>
                </div>
              </td>
              <td>
                <div class="sg-biz sg-biz-1col">
                  <div><span>销量</span><b>{{ zero(p.sold30) }}</b></div>
                  <div><span>总销量</span><b>{{ zero(p.sales) }}</b></div>
                </div>
              </td>
              <td>
                <div class="sg-status">
                  <span class="sg-dot" :style="{ background: SG_STATUS_META[p.status].dot }" />
                  <span :style="{ color: SG_STATUS_META[p.status].color }">{{ SG_STATUS_META[p.status].label }}</span>
                </div>
                <div v-if="p.status === 'auditFail'" class="sg-failtag" :title="p.rejectReason">
                  审核未通过 <i class="sg-fail-i" :title="p.rejectReason">i</i>
                </div>
                <div v-else-if="p.offType" class="sg-offtag" :class="isFailOff(p) ? 'fail' : 'normal'">
                  {{ SG_OFF_GROUP[p.offType] }}
                </div>
              </td>
              <td>{{ p.strategy }}</td>
              <td>
                <div v-if="p.offType && sgWarnType(p)" class="sg-offtag" :class="isFailOff(p) ? 'fail' : 'normal'" @mouseenter="showOffPop($event, p.offReason ?? '')" @mouseleave="hideOffPop">
                  {{ sgWarnType(p) }} <i class="sg-fail-i">i</i>
                </div>
                <span v-else class="sg-dash">-</span>
              </td>
              <td>
                <div class="sg-kv"><span class="sg-kv-l">发布人：</span><b>{{ p.publisher }}</b></div>
                <div class="sg-kv sg-kv-store">
                  <span class="sg-kv-l">发布店铺：</span>
                  <span class="store-logo"><img :src="PLATFORM_LOGO[p.storePlatform]" alt="" /></span>
                  <b>{{ p.store }}</b>
                </div>
                <div class="sg-kv"><span class="sg-kv-l">发布方式：</span><b>{{ p.publishMode ?? '-' }}</b></div>
                <div class="sg-kv">
                  <span class="sg-kv-l">{{ p.offTime ? '下架时间：' : p.shelfTime ? '上架时间：' : '发布时间：' }}</span>
                  <b>{{ p.offTime ?? p.shelfTime ?? p.publishTime }}</b>
                </div>
              </td>
              <td>
                <div class="sg-acts">
                  <a
                    v-for="a in rowActions(p)"
                    :key="a"
                    class="sg-link"
                    href="javascript:void(0)"
                    @click.prevent="a === '商品详情' ? (detail = p) : null"
                  >
                    {{ a }}
                  </a>
                  <a
                    v-if="sgWarnType(p)"
                    class="sg-link"
                    href="javascript:void(0)"
                    @click.prevent="relTarget = p"
                  >关联商品</a>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
        <div v-if="rows.length === 0" class="sg-empty">
          <div class="sg-empty-wrap">
            <div class="sg-empty-icon">◌</div>
            <div>暂无数据，请调整筛选条件</div>
          </div>
        </div>
      </div>
    </div>

    <div class="pm-page pm-host">
      <SgBatchPriceModal
        v-if="bpOpen && sellingSel > 0"
        :count="sellingSel"
        @close="bpOpen = false"
        @ok="pushToast"
      />
    </div>

    <div v-if="offPop.show" class="sg-fail-pop" :style="{ left: offPop.x + 'px', top: offPop.y + 'px' }">
      <p>{{ offPop.text }}</p>
    </div>

    <CwRelDrawer :product="relTarget" @close="relTarget = null" />
  </div>
</template>
