// src/App.tsx
import { useCallback, useMemo, useState } from 'react';
import { navigation } from './config/navigation';
import TopTabs from './components/TopTabs';
import Sidebar, { findFirstLeaf } from './components/Sidebar';
import QualityCenter from './pages/quality/QualityCenter';
import AppCenter from './pages/app-center/AppCenter';
import OpsCenter from './pages/ops-center/OpsCenter';
import ReceptionCenter from './pages/reception/ReceptionCenter';
import './App.css';

export default function App() {
  const [activeTabKey, setActiveTabKey] = useState('ops-center');
  const [activeMenuKey, setActiveMenuKey] = useState('');
  const [sidebarCollapsed, setSidebarCollapsed] = useState(() => {
    try { return localStorage.getItem('funion:sidebarCollapsed') === 'true'; }
    catch { return false; }
  });

  const toggleSidebar = useCallback(() => {
    setSidebarCollapsed((v) => {
      const next = !v;
      try { localStorage.setItem('funion:sidebarCollapsed', String(next)); } catch {}
      return next;
    });
  }, []);

  const activeTab = useMemo(
    () => navigation.find((tab) => tab.key === activeTabKey) ?? navigation[0],
    [activeTabKey],
  );

  const handleTabChange = (key: string) => {
    const tab = navigation.find((t) => t.key === key);
    if (!tab) return;
    setActiveTabKey(tab.key);
    setActiveMenuKey(findFirstLeaf(tab.menus)?.key ?? '');
  };

  return (
    <div className="app-layout">
      <header className="app-header">
        <div className="app-logo">Funion</div>
        <TopTabs
          tabs={navigation}
          activeKey={activeTabKey}
          onChange={handleTabChange}
        />
        <div className="app-header-right">
          <span className="app-avatar" />
          <span className="app-username">七妮妮</span>
          <div className="app-window-dots">
            <button type="button" className="app-dot minimize">
              −
            </button>
            <button type="button" className="app-dot maximize">
              +
            </button>
            <button type="button" className="app-dot close">
              ×
            </button>
          </div>
        </div>
      </header>
      <div className="app-body">
        {activeTabKey === 'ops-center' ? (
          <main className="app-content">
            <OpsCenter sidebarCollapsed={sidebarCollapsed} onToggleSidebar={toggleSidebar} />
          </main>
        ) : activeTabKey === 'qc-center' ? (
          <main className="app-content qc-standalone">
            <QualityCenter sidebarCollapsed={sidebarCollapsed} />
          </main>
        ) : activeTabKey === 'app-center' ? (
          <main className="app-content ac-standalone">
            <AppCenter />
          </main>
        ) : activeTabKey === 'reception-center' ? (
          <main className="app-content ac-standalone">
            <ReceptionCenter sidebarCollapsed={sidebarCollapsed} />
          </main>
        ) : (
          <>
            <Sidebar
              menus={activeTab.menus}
              activeKey={activeMenuKey}
              onSelect={setActiveMenuKey}
              className={sidebarCollapsed ? 'collapsed' : ''}
            />
            <main className="app-content" />
          </>
        )}
      </div>
    </div>
  );
}

// src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import { navigation } from './config/navigation';
import TopTabs from './components/TopTabs.vue';
import ReceptionCenter from './pages/reception/ReceptionCenter.vue';
import QualityCenter from './pages/quality/QualityCenter.vue';
import AppCenter from './pages/app-center/AppCenter.vue';
import OpsCenter from './pages/ops-center/OpsCenter.vue';
import './App.css';

const readCollapsed = () => {
  try { return localStorage.getItem('funion:sidebarCollapsed') === 'true'; }
  catch { return false; }
};

const activeTabKey = ref('ops-center');
const sidebarCollapsed = ref(readCollapsed());

const toggleSidebar = () => {
  sidebarCollapsed.value = !sidebarCollapsed.value;
  try { localStorage.setItem('funion:sidebarCollapsed', String(sidebarCollapsed.value)); } catch { /* 忽略隐私模式异常 */ }
};

const handleTabChange = (key: string) => {
  const tab = navigation.find((t) => t.key === key);
  if (!tab) return;
  activeTabKey.value = tab.key;
};

defineExpose({ toggleSidebar });
</script>

<template>
  <div class="app-layout">
    <header class="app-header">
      <div class="app-logo">Funion</div>
      <TopTabs
        :tabs="navigation"
        :active-key="activeTabKey"
        :on-change="handleTabChange"
      />
      <div class="app-header-right">
        <span class="app-avatar" />
        <span class="app-username">七妮妮</span>
        <div class="app-window-dots">
          <button type="button" class="app-dot minimize">
            −
          </button>
          <button type="button" class="app-dot maximize">
            +
          </button>
          <button type="button" class="app-dot close">
            ×
          </button>
        </div>
      </div>
    </header>
    <div class="app-body">
      <!-- 四个顶部 tab 均已完成 Vue 移植（原 .vue-pending 占位分支已移除） -->
      <template v-if="activeTabKey === 'reception-center'">
        <main class="app-content ac-standalone">
          <ReceptionCenter :sidebar-collapsed="sidebarCollapsed" />
        </main>
      </template>
      <template v-else-if="activeTabKey === 'qc-center'">
        <main class="app-content qc-standalone">
          <QualityCenter :sidebar-collapsed="sidebarCollapsed" />
        </main>
      </template>
      <template v-else-if="activeTabKey === 'app-center'">
        <main class="app-content ac-standalone">
          <AppCenter />
        </main>
      </template>
      <template v-else-if="activeTabKey === 'ops-center'">
        <main class="app-content">
          <OpsCenter />
        </main>
      </template>
    </div>
  </div>
</template>
